### ISSUE TITLE
When does a Resource become a new Resource

### ISSUE THREAD

**Issue by bhaugen** [valueflows/resource#11]
Or, what is the definition of "the same resource".
- For example, if a resource is transferred to a new owner, is it the same resource?
  - If it has a serial number or lot ID, it's the same resource with a new owner.
    - But what if the lot is split and you become the new owner of part of the lot and somebody else becomes the new owner of the other part of the lot. Are they the same resource?
  - But what if it is a bin of flour in the coop grocery and you take some of it home. Is it the same resource?
- How about if it is moved to a new location?
  - Same sub-questions as a new owner.
- How about if it is repaired and has a lot of new parts?
- What if the resource becomes part of another resource?
  - If it has a serial number and can still be identified and detached, it's the same resource.
  - If it's paint, is it the same resource?
- What if it's a new version of something like software?
- What other similar questions have you encountered?
- Is there an ontological category that this issue fits into? Like mereology for part/whole relationships?
  - If there is, will it help to study it? (I can't say that reading about mereology helped me any...)

**Comment by fosterlynn** [comment]
Very interesting set of questions.  Thinking about some examples because in re-modeling exchange, I'm thinking a Transfer is 2 events, a give and a take (receive), instead of one.  Split lots are confirming that for me.

I think the split lot example creates a new resource.  If the coop has a bin of 50 lbs of whole wheat flour, that is one resource.  If someone buys 5 lbs of that flour, the 5 lbs is a new resource.  The bin of flour in the coop is still the same resource it was, but it has quantity of 45 instead of 50.

If I have a case of say jars sitting on a pallet, with a lot number, that is a resource.  If I sell you 5 jars, the case of jars on the pallet is still the same resource, as above, with less quantity.  The 5 jars you have now is a new resource.  But it still carries the same lot number.

Some resources are more strongly identified than others - the car VIN 12345 that you gave to me (thanks!) is the same resource when you owned it and when I owned it.  The bin of flour is more identified by bin location and resource type.

**Comment by ahdinosaur** [comment]
from @gcassel in https://github.com/valueflows/valueflows/issues/103#issuecomment-217014167

> To be really nitty gritty about it, transformation doesn't always create "new" resources.  Sometimes IMO it just modifies the attributes of a resource.  For instance, we could describe teeth-cleaning as not only a service, but a transformation of someone's teeth.  We wouldn't necessarily *need* to, but, I think that that's the rational way to be more detailed about a teeth-cleaning process.

> (Otherwise, I currently think that it's hard to formally associate some types of service with specific enduring resources...)

> Looking deeper, technically, transformation is often an act of fusion or fission of previously identified resources.  As an example, hopefully not insulting anyone's excellent intelligence:
2 Na + Cl<sup>2</sup>(g)  > 2 NaCl 

> Sodium and chlorine are agents, as atoms or as molecules, but can be combined to form the "new" agent of sodium chloride / table salt.   The previous agents are still there, but bound in an unusually stable dependency.  The previous agents have acquired new attributes/ relationships.

> I guess this is my roundabout way of suggesting that ultimately, transportation is fundamentally a subclass of transformation from my personal perspective.  IMO it's all ultimately a matter of the properties and attributes of each agent.   

> Simple agents have few properties, but may have many attributes.  Complex agents may have many properties, including the relationships of simpler agents which *create* the complex agent.   Complex agents may also have many attributes.

> Anyway, IMO "location" is simply an attribute of an agent; and that attribute can be changed/ transformed.

**Comment by gcassel** [comment]
^ indebted to your mapping, navigation and link skills here; thanks @ahdinosaur .

In the context of this topic, I guess I'd say that a resource (or group of resources) becomes a "new" resource through fusion or fission of other resources which can be identified.  

Creative work/ informational resources may seem almost to spring out of nowhere.  For instance, someone shares a new idea, or writes a poem.   I think that's where accounting gets really tricky, and probably less useful.   Material resources are much easier to track... it's just really time-consuming to go into deeper levels of description and tracking.

**Comment by bhaugen** [comment]
My view of this is to track what is useful to track, which is really really context dependent.

For example, we got some networks that want to track maybe a thousand times more than other networks. I could name names, but won't. Sometimes depends on the administrative experience of the people. Like, did you catch minimalism yet, or not?

**Comment by gcassel** [comment]
I agree entirely to simply track what is useful to track in a given context.   However, any time a person or group pretends that a resource has magically appeared in a way which can't be connected to previous resources and agents, I believe they're at imminent risk of engaging in unsustainable processes.    

There are shortcuts and heuristics to use at any level of analysis, which are fine as long as valued work or contributed resources aren't ignored.
