### ISSUE TITLE
identifying a resource

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#13]
Currently I can think of two ways of identifying a resource in VF environment:

1) IRI ([direct identification](https://www.w3.org/TR/webarch/#id-resources)) https://tools.ietf.org/html/rfc3987
2) Blank node ([indirect identification])(https://www.w3.org/TR/webarch/#indirect-identification)) https://www.w3.org/TR/rdf11-concepts/#section-blank-nodes

In first case a resource has it's own distinct identity and we can always denote it using IRI

``` jsonld
{ 
  "@context": "https://w3id.org/valueflows/v1",
  "@id": "did:be9f6712-9bda-4f68-a21e-c05e3d415cbe",
  "@type": "vf:Resource"
}
```

In second case, let's say 5kg of apples in particular pile, we can only identify a resource as a part of a _Stock_. In that case a stock needs to have IRI and we use blank node to indirectly identify a resource

``` jsonld
{
  "@context": "https://w3id.org/valueflows/v1",
  "@type": [ "vf:Resource", "prodont:Apple"],
  "vf:amount": 5,
  "vf:unit": "unit:Kilogram",
  "vf:inStock": {
    "@id": "did:b8ecb4b1-727e-4c5b-a6e2-cd10dd726840",
    "@type": "vf:Stock",
    "vf:location": "https://osm.org/node/23423421114"
  }
}
```

In examples I used [A Decentralized Hashtable for the Web](http://opencreds.org/specs/source/webdht/) URI scheme `did:`. With `http:` we have this issue of ownership of domain etc. which can make harder to transfer rights to resources while keeping URIs unchanged. Let's for now just assume IRI and later we can look how to combine various available schemes `http:`, `did:`, `urn:uuid:` etc.

**Comment by bshambaugh** [comment]
What is the document that we are talking about in the @id? Does the first
case exclude the second?

-Brent Shambaugh

Website: bshambaugh.org

**Comment by elf-pavlik** [comment]
I updated the first case to add `"@type": "vf:Resource"`. I just try to emphasise difference between direct and indirect identification explained in https://www.w3.org/TR/webarch/#indirect-identification

In some cases resource we want to identify doesn't have distinct IRI, in such cases we can use indirect identification by describing it as part of a resource which does have IRI, in example above a stock.

**Comment by bshambaugh** [comment]
Okay, so basically in the second

_bn vf:inStock

did:b8ecb4b1-727e-4c5b-a6e2-cd10dd726840

"@id": "did:b8ecb4b1-727e-4c5b-a6e2-cd10dd726840"

* is in stock*and ..

*did:b8ecb4b1-727e-4c5b-a6e2-cd10dd726840 vf:location *
*"https://osm.org/node/23423421114 <https://osm.org/node/23423421114>"*

*In the first, *
"did:be9f6712-9bda-4f68-a21e-c05e3d415cbe"  is part of the WebDHT

per the http://opencreds.org/specs/source/webdht/#dfn-webdht


-Brent Shambaugh

Website: bshambaugh.org

**Comment by bhaugen** [comment]
The discussion above so far focuses mostly on the technicalities of resource identification. While those are important, so are the semantics of resource identification, which depend on the resource type.

Resources often have both a tracking identifier and a stock-keeping identifier. The tracking identifier accompanies with the resource wherever it goes. (Where "it" will also depend on whether it is serialized, one unique resource, or a member or members of a batch or lot.) The stock-keeping identifier includes its current location.

Examples:
* A large batch of stew that ends up in many containers sent to many places and is ultimately found to contain botulism. Public health workers will want to find all containers that came from that batch.
* A computer with a serial number that goes with @elf-pavlik on his various adventures that has a defective part under warranty. To get a replacement part, Pavlik will need to send the serial number.
* A bin containing a kilo of bolts that are all the same.
* A dairy goat named Molly.
* A field of beans that are ready for harvest.

**Comment by elf-pavlik** [comment]
> The discussion above so far focuses mostly on the technicalities of resource identification. While those are important, so are the semantics of resource identification, which depend on the resource type.

Do you see need for other identification mechanism than two I proposed
1) direct - IRI
2) indirect - clearly defined part of a stock which does have IRI

> * A large batch of stew that ends up in many containers sent to many places and is ultimately found to contain botulism. Public health workers will want to find all containers that came from that batch.

Batch of stew should have IRI, later it goes as input to packaging process which outputs those many containers, preferably each of them should have IRI (eg. with QR code label on each container)

> * A computer with a serial number that goes with @elf-pavlik on his various adventures that has a defective part under warranty. To get a replacement part, Pavlik will need to send the serial number.

that computer should have IRI (direct) and `@type` equivalent to [schema:IndividualProduct](https://schema.org/IndividualProduct)

> * A bin containing a kilo of bolts that are all the same.

a stock containing that bin with bolts should have IRI (direct), each bolt indirect as piece in that stock

> * A dairy goat named Molly.

should have IRI (direct)

> * A field of beans that are ready for harvest.

the particular field should have IRI eg. http://linkedgeodata.org/ (direct), beans itself indirect as part of the field (stock)

So far seems that direct and indirect (as part of stock) identification covers all those cases!

**Comment by bhaugen** [comment]
Ok with me. Can Molly have something on her collar?

**Comment by elf-pavlik** [comment]
> Ok with me. Can Molly have something on her collar?

* collar
* earring
* chip under the skin

Or since the person who takes care of her, can manage the mapping to IRI. In case where something goes 'wrong' and no one can recognise Molly's identity, she would get new name e.g Tina and new IRI. Then at some point if someone realizes that Molly == Tina [owl:sameAs](https://www.w3.org/TR/owl2-primer/#Equality_and_Inequality_of_Individuals) can help with reconciling IRIs.

**Comment by bhaugen** [comment]
Molly says "b-a-a-a-a-a-ah"

**Comment by elf-pavlik** [comment]
Molly seems more and more `"@type": "vf:Agent"` than `"@type": "vf:Resource"` :wink:

**Comment by fosterlynn** [comment]
Maybe Molly would like to join our project....

**Comment by elf-pavlik** [comment]
To clarify, same stock can 'contain' multiple resources
```json
{
  "@context": "https://w3id.org/valueflows/v1",
  "@graph": [
    {
      "@type": [ "vf:Resource", "prodont:Apple"],
      "vf:amount": 5,
      "vf:unit": "unit:Kilogram",
      "vf:inStock": {
        "@id": "did:b8ecb4b1-727e-4c5b-a6e2-cd10dd726840",
        "@type": "vf:Stock",
        "vf:location": "https://osm.org/node/23423421114"
      }
    },
    {
      "@type": [ "vf:Resource", "prodont:Apple"],
      "vf:amount": 20,
      "vf:unit": "unit:Kilogram",
      "vf:inStock": {
        "@id": "did:b8ecb4b1-727e-4c5b-a6e2-cd10dd726840",
        "@type": "vf:Stock",
        "vf:location": "https://osm.org/node/23423421114"
      }
    },
    {
      "@type": [ "vf:Resource", "prodont:Apple"],
      "vf:amount": 3.5,
      "vf:unit": "unit:Kilogram",
      "vf:inStock": {
        "@id": "did:b8ecb4b1-727e-4c5b-a6e2-cd10dd726840",
        "@type": "vf:Stock",
        "vf:location": "https://osm.org/node/23423421114"
      }
    }
  ]
}
```

system just needs to prevent creating resources with sum of amounts bigger than the amount actually in the stock

**Comment by elf-pavlik** [comment]
related: https://github.com/valueflows/valueflows/issues/126
