### ISSUE TITLE
Faircoin

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#18]
Looking at use case: https://github.com/valueflows/valueflows/blob/master/use-cases/digital_currency.md

> Both Bob's address and Lynn's address are Economic Resources.

resources or stocks which contain resources?

> - Bob has rights to the amount of FCs in his address, and Lynn has already had rights to those in hers.

does the address link in any way to person's identity, or anyone who has access to that address (crypto key?) can control it?

> - If and then the transaction is confirmed, Bob's balance will be decremented by 2 FCs and Lynn's balance will be incremented by 1.999 FCs.

each person can have multiple addresses, also as I understand one can loose access to an address (by loosing crypto key?), so addresses balances change, relation to any identity lik Bob or Lynn seems not formalized

> - The amount of FCs on the transaction to Lynn (1.999) is not an Economic Resource. Nobody can use it. It is just a record of the amount by which Lynn's balance will increase if the transaction succeeds.

If Lynn exchanged 2L of apple juice for 2 Faircoins, why don't we consider those 2 Faircoins a _vf:Resource_ just as 2L of apple juice?

**Comment by bhaugen** [comment]
>> Both Bob's address and Lynn's address are Economic Resources.

> resources or stocks which contain resources?

It's ambiguous. We need to decide how to define resources. Bill McCarthy never instantiates resources. For him, they are derived from Economic Event history. I generally do instantiate resources in software the same way as ERP systems, depending on the specificity of the resource identifiers.

So if it's a serialized resource (e.g. each individual has a different serial number), then that's the resource. If a group of resources are identified by a lot or batch id, then it's a stock idenfiied by a combination of the lot id and the location. If it's a count or volume resource (nuts and bolts), it's a stock location.

Since FairCoins are count resources, each address is a resource in our current software. That does not need to be the way VF does it, though.

>> * Bob has rights to the amount of FCs in his address, and Lynn has already had rights to those in hers.

> does the address link in any way to person's identity, or anyone who has access to that address (crypto key?) can control it?

The address is part of a wallet, but anyone who has access to the wallet can control it.

>> * If and then the transaction is confirmed, Bob's balance will be decremented by 2 FCs and Lynn's balance will be incremented by 1.999 FCs.

> each person can have multiple addresses, also as I understand one can loose access to an address (by loosing crypto key?), so addresses balances change, relation to any identity lik Bob or Lynn seems not formalized

We formalize it in an software object that is outside the FairCoin environment, but it is not so identified inside the FairCoin environment.

>> * The amount of FCs on the transaction to Lynn (1.999) is not an Economic Resource. Nobody can use it. It is just a record of the amount by which Lynn's balance will increase if the transaction succeeds.

> If Lynn exchanged 2L of apple juice for 2 Faircoins, why don't we consider those 2 Faircoins a *vf:Resource* just as 2L of apple juice?

Those Faircoins would just be a number that was subtracted from some other FC address and added to Lynn's FC address. They cannot be spent from the transaction enroute.

Rights to the 2L of apple juice would, if we are being consistent, would be transferred from Lynn to somebody, and then the physical 2L of apple juice would be transported or moved somehow from Lynn to somebody. The transported 2L of apple juice would be a resource in transportation (somebody else could drink it enroute, unlike the faircoins), but whether the rights in transfer were a resource depends on if we define rights as a resource or not.

**Comment by elf-pavlik** [comment]
> Rights to the 2L of apple juice would, if we are being consistent, would be transferred from Lynn to somebody, and then the physical 2L of apple juice would be transported or moved somehow from Lynn to somebody. The transported 2L of apple juice would be a resource in transportation (somebody else could drink it enroute, unlike the faircoins), but whether the rights in transfer were a resource depends on if we define rights as a resource or not.

Do you treat Faircoin in a similar way as you treat USD? (USD in AccountCredit representation, not printed Cash which makes just a tiny fraction of USD - https://github.com/elf-pavlik/currency/issues/2)

from https://github.com/valueflows/valueflows/issues/117
> Also in our distinction between actual resource and rights to that resource. Monetary currencies seem more of a rights to a resource, often without any clear 'underlying resource'.

**Comment by bhaugen** [comment]
> Do you treat Faircoin in a similar way as you treat USD? (USD in AccountCredit representation, not printed Cash which makes just a tiny fraction of USD - elf-pavlik/currency#2)

I think so.

> Also in our distinction between actual resource and rights to that resource. Monetary currencies seem more of a rights to a resource, often without any clear 'underlying resource'.

I think they are rights to an account, which is a count resource (in the rough classification I listed above).

One of the aspects that is dawning on me as we tease this stuff apart is how much the types of flows (the way they flow, the event behaviors) depend on the resource type.

**Comment by elf-pavlik** [comment]
https://github.com/valueflows/exchange/blob/master/Transfer.md
> vf:Transfer
Moving rights to and responsibilities for an economic resource from one agent to another. This does not cover change of location.

If agent does *vf:Transfer* of 2Faircoin or 10USD to another agent. Do we consider those 2Faircoins or 10USD as *economic resource* in "Moving rights to and responsibilities for an economic resource from one agent to another."

BTW *vf:Transfer* may trigger relocation (*vf:Transportation*) of that virtual/digital resource or may not. As shown in following use case, *vf:Transfer* of digital currency can happen within same account/digital_walet [Currency exchange (ISO4217)](https://github.com/valueflows/valueflows/blob/master/use-cases/currency-exchange-iso4217.md) Similar Faircoin<->Bitcoin *vf:Exchange* could happen within single Faircoin and single Bitcoin wallet shared by two agents.

**Comment by bhaugen** [comment]
>  Faircoin<->Bitcoin vf:Exchange could happen within single Faircoin and single Bitcoin wallet, both shared by two agents doing that exchange.

That is in fact what is happening in our current Faircoin app. Many agents have accounts (addresses) in the same wallet.

> If agent does vf:Transfer of 2Faircoin or 10USD to another agent. Do we consider those 2Faircoins or 10USD as economic resource mentioned in "Moving rights to and responsibilities for an economic resource from one agent to another."

In the case of digital (or probably other currencies that are basically money-of-account) that definition of transfer seems inaccurate or inadequate. It might be either that vf:Transfer covers the behavior of some flows for some resource types, and does not cover others. Or the definition needs more work.

This definition stuff is hard...

**Comment by elf-pavlik** [comment]
> In the case of digital (or probably other currencies that are basically money-of-account) that definition of transfer seems inaccurate or inadequate. It might be either that vf:Transfer covers the behavior of some flows for some resource types, and does not cover others.

I understand that you prefer not to consider "5USD on BankAcount nr. 3424242342" or "2Faircoin on adress 312340149140" as *vf:Resource* (aka *Economic Resource*)?

**Comment by bhaugen** [comment]
> I understand that you prefer not to consider "5USD on BankAcount nr. 3424242342" or "2Faircoin on adress 312340149140" as vf:Resource (aka Economic Resource)?

If you mean the numbers on transactions in process, they are not spendable. Thus, not actually money  resources. If you mean the numbers in actual accounts that are spendable, they are economic resources. It's at least partly about what you can or cannot do with them.

**Comment by fosterlynn** [comment]
>It might be either that vf:Transfer covers the behavior of some flows for some resource types, and does not cover others. Or the definition needs more work.

I think we should broaden and also clarify the definition.  We need to do that for service transfers too.  And work on the definitions of Resource etc. at the same time, clarifying the various stock / flow concepts.

I can plug in more on it in a day or so.

**Comment by elf-pavlik** [comment]
> If you mean the numbers on transactions in process, they are not spendable. Thus, not actually money resources. If you mean the numbers in actual accounts that are spendable, they are economic resources. It's at least partly about what you can or cannot do with them.

I wrote
> "5USD on BankAcount nr. 3424242342" or "2Faircoin on address 312340149140"

so the digits 'on' particular account/address, which I understand you do consider vf:Resource (*economic resource*)


I understand that by 'spendable' you mean that one can put them into a 'transaction in process' again? Can we see this 'transaction in process' as digital shipping/delivery - it leaves one storage place and arrives to another storage place.

**Comment by bhaugen** [comment]
Agreed.

**Comment by bhaugen** [comment]
More about stocks and flows: REA creates stock-and-flow systems, where resources are stocks, and economic events are flows. In fact, the relationship between resource and event in REA is stockflow, and several people we know who create REA-based software create Stockflow objects. I did, too, in my first REA-based software, but then got over it because the economic event is sufficient.

But, being a stock-and-flow system means that a large range of analytical methods become available,  such as [network flows](https://en.wikipedia.org/wiki/Flow_network), [system dynamics](https://en.wikipedia.org/wiki/System_dynamics), and (I think) [process calculus](https://en.wikipedia.org/wiki/Process_calculus).

You can see examples in [this article I wrote in 2005](http://mikorizal.org/BeyondTheEnterprise.html) when I was just starting to think about what to do when I retired.

**Comment by elf-pavlik** [comment]
>>  Faircoin<->Bitcoin vf:Exchange could happen within single Faircoin and single Bitcoin wallet, both shared by two agents doing that exchange.

> That is in fact what is happening in our current Faircoin app. Many agents have accounts (addresses) in the same wallet.

Can you do vf:Transfer within a single faircoin address? So no faircoin:Transaction happens, the valueflow environment does everything internally. Just vf:Transfer of rights to certain amounts of Faircoins stored and the same address. No vf:Transportation based on faircoin:Transaction to **move** Faircoins between two different addresses.

**Comment by bhaugen** [comment]
> Can you do vf:Transfer within a single faircoin address?

I think so. The change output can go back to the same address. But for the main amount to be decremented from the origin address and then incremented back into the same address, minus network fee, what would be the point?

**Comment by elf-pavlik** [comment]
> what would be the point?

No! faircoin:Transaction doesn't even happen at all. In your valueflows environment you just do vf:Transfer and done, Faircoin system doesn't even know that anything changed...

In similar way https://transferwise.com do many clearings as their internal transactions. They minimise movement (vf:Transportation) of ISO4217 currencies between accounts. As I understand they also do some currency exchanges internally, similar to [Currency exchange (ISO4217)](https://github.com/valueflows/valueflows/blob/master/use-cases/currency-exchange-iso4217.md)

**Comment by bhaugen** [comment]
> No! faircoin:Transaction doesn't even happen at all. 

Missed that part, sorry. Would have helped to explain that you are thinking abut clearing. That would be a good use case.

**Comment by gcassel** [comment]
Thanks for referring me to this thread on the Sunday call.

I'm very interested in however we come to use terms such as wallet, account, address, stock and/or inventory in the future.  

I understand obviously that coders have to work with various local taxonomies such as Faircoin stuff.   FWIW though, I'm currently thinking that it's probably possible for VF to use only one term-- such as "account"-- to indicate any number of potential relationships (use rights and responsibilities) which a specific (individual or group) agent may have with specific stocks and serialized resources.

It's certainly possible that I'm missing something!

**Comment by bhaugen** [comment]
So far, I have not seen any groundswell for vf to define account or wallet.
