### ISSUE TITLE
ResourceType taxonomy

### ISSUE THREAD

**Issue by bhaugen** [valueflows/resource#20]
For example, http://aims.fao.org/standards/agrovoc
or http://www.productontology.org/
or...?

**Comment by elf-pavlik** [comment]
Please notice difference between SKOS concepts defined in AGROVOC and OWL classes defined in Product Ontology e.g http://www.productontology.org/doc/Apple.html

Once again https://www.w3.org/2006/07/SWD/SKOS/skos-and-owl/master.html

I do want to use heavily https://www.wikidata.org/ - check out it's autocomplete, friend started a small lib which will allow to use such wikidata based autocomplete in independent HTML5 apps.

Freebase merged into Wikidata https://plus.google.com/109936836907132434202/posts/bu3z2wVqcQc
