### ISSUE TITLE
Defining vf:EconomicResource

### ISSUE THREAD

**Issue by bhaugen** [valueflows/resource#23]
First, I think we should use the name EconomicResource since the undifferentiated name Resource is associated so strongly with Resource in Resource Description Framework (RDF).

Second, I want to try out using rea:Name as the namespace (even if that namespace does not exist yet) for REA concepts that we are basing a vf:Name on, at least partly, and also at the same time to explain how we are varying from the REA definition, because in many cases we need to do so. 

I'll get my REA definitions from [The REA Accounting Model](https://msu.edu/user/mccarth4/McCarthy.pdf), [The Ontological Foundation of REA Enterprise Information Systems](https://msu.edu/user/mccarth4/Alabama.doc) or the [ISO Accounting and economic ontology](https://msu.edu/user/mccarth4/15944-4.doc), which was also based on REA but modified by a committee of e-commerce experts from around the world. ISO has pretty clear definitions.

rea:Economic Resource: 
![image](https://cloud.githubusercontent.com/assets/117439/15366697/2b3678f4-1ceb-11e6-9430-26da2313fc87.png)

iso:Economic Resource 

> An Economic Resource is a scarce good, right, or service that possesses utility (economic value) and that is presently under the identifiable control of a particular Person

iso:Person

> A Person is a natural or legal person or organizational unit empowered to control the flow of economic resources (including his or her own labor) by engaging in economic events.  

We can't use those definitions as-is, because Economic Resources that have utility for economic networks are often not scarce. (That part of the REA and ISO definitions is just out of date.) And if we want to include whole ecosystems in our analysis, they may not be under the identifiable control of any person or enterprise.

For discussion, I would start with:
vf:EconomicResource is a tangible or intangible good or service that possesses utility (economic value) to an EconomicAgent.

(I want to leave rights out of it for now, because I don't think everybody here agrees on rights as an EconomicResource, and we have been exploring an alternative model that focuses more on responsibilities and coordination and does not require the concept of ownership.)

Another aspect of the definition is the identification of a vf:EconomicResource (https://github.com/valueflows/resource/issues/13).

@elf-pavlik proposed two means of identification:
1) direct - IRI
2) indirect - clearly defined part of a stock which does have IRI

I have proposed three different types of resources from the viewpoint of identification:
a) serialized resources, where each individual instance has a unique identifier,
b) lot-controlled resources, where each lot or batch has a unique identifier, but the lot or batch may contain many individual instances, and
c) count or volume or stock resources, where individual instances are indistinguishable, or in the case of fluids, only exist on a molecular level.

Serialized resources would fit the direct identification pattern. Lots can be split up, so the identification of a subset of a lot would require some other properties, such as location. Stock resources can only be described indirectly, by means of some combination of properties, such as vf:ResourceType and location. (Location is a complex ontology of its own: for example, in warehousing, a location is often composed of warehouse:room:aisle:row:tier.)

Moreover, identification of resources will depend on context and purpose. I think we need to allow each context to define resources that they have relationships with, according to the combination of properties that works best for them, which might include which agent has which relationship with a resource. 

And then in the "independent view", for larger-scale analysis of resource flows, or for example for lot tracking for public health issues like mad cow disease, different combinations of properties might be needed.

**Comment by fosterlynn** [comment]
>For discussion, I would start with:
vf:EconomicResource is a tangible or intangible good or service that possesses utility (economic value) to an EconomicAgent.

I like it except would just say Agent, and not revisit that name.  Also if something comes up better than "good", that seems a little product-like.  But if not, I won't sweat it.

**Comment by bhaugen** [comment]
I'm good with Agent. If anybody has anything better than good, I'm good with that, too.

**Comment by bhaugen** [comment]
One corollary to all this vf:EconomicResource definition and identification stuff is that vf:Agents who want to coordinate and collaborate will need to agree on definitions and identification schemes. This is why [GTINs](http://www.gtin.info/) and similar schemes exist.

**Comment by elf-pavlik** [comment]
> First, I think we should use the name EconomicResource since the undifferentiated name Resource is associated so strongly with Resource in Resource Description Framework (RDF).

We don't try to define *Resource*, Wikipedia does pretty good job with managing 'global namespace' but we define *vf:Resource* where the `vf:` namespace implies focus on economy. I hope we will not need to use *vf:EconomicProcess*, *vf:EconomicTransfer* etc. If someone says/writes just *process* or *transfer* we can assume that person intends to use the Wikipedia definition.

> Location is a complex ontology of its own: for example, in warehousing, a location is often composed of warehouse:room:aisle:row:tier

We can simply require that any *Place* (Location) has IRI and we can identify it directly. How people map their IRIs to shelves and drawers shouldn't concern us. If we can identify it in VF environment, we do it by IRI. If we want to 'bind' location to a vehicle or a person. We would use IRI to identify that vehicle or person.

**Comment by bhaugen** [comment]
So far, I think that EconomicResource is the only one we need to qualify, unless we use Event. In that case, we also need to qualify EconomicEvent, But I think we need to do that. And it is different from other versions of Resource (or Event). I think you are wrong that it will not be confusing if we do not qualify it. I have run into this in a lot of settings, and both are always confusing if not qualified, and sometimes confusing even if qualified, because people enjoy being confused.

**Comment by ahdinosaur** [comment]
> I think you are wrong that it will not be confusing if we do not qualify it. I have run into this in a lot of settings, and both are always confusing if not qualified, and sometimes confusing even if qualified, because people enjoy being confused.

hm, i haven't had a problem yet while explaining unqualified terms, i just preface everything with "these terms are how we describe things in Value Flows land".

**Comment by ahdinosaur** [comment]
@bhaugen what if we made a point to always use the vf: prefix even when talking in human language words? it seems we have been naturally doing it, but if we formalized this so every term was qualified via the prefix, would that help?

**Comment by bhaugen** [comment]
Don't know. People don't tend to use prefixes in any setting that they are not required to do so.

I have had continually problems with resource and event over the years, so depending on the context, I often qualify that I am talking about an economic resource or economic event and not that other definition of event or resource.

But in general, I would not block an otherwise consensus agreement on almost whatever.

**Comment by gcassel** [comment]
The "economic event" concept is a very distinctive deviance from how most people use the term.  For instance, in agreement-based organization I use this definition: 
>1.6.6 Events indicate occasions, of any duration, during which special conditions and/or activities will persist.

^IMO that's pretty nearly the normal perspective of a "social event" or organized event.

So, I think maybe it's important to often (but not universally) specify "economic event" to indicate that there's a certain conceptual discipline involved.   It's definitely an important discipline, regardless of the nomenclature used.   

It certainly seems to me that "vf: event" would create effective communication in a wide variety of contexts.

**Comment by fosterlynn** [comment]
>1.6.6 Events indicate occasions, of any duration, during which special conditions and/or activities will persist.

Yes for sure this is how most people use it.  I'm hoping we can find a better word than Event, that is also not EconomicEvent.  Maybe Flow or ResourceFlow or ValueFlow, although that has been a bit confusing too.

**Comment by ahdinosaur** [comment]
oh, i use events as [event-based programming](https://en.wikipedia.org/wiki/Event-driven_programming) or when talking about [lambda architecture as an append-only database of events](https://martin.kleppmann.com/2015/03/04/turning-the-database-inside-out.html). :smile:

**Comment by gcassel** [comment]
I guess that "transition" would be okay instead of economic "event",  but then we'd have transfer, transportation, transformation, transition...   maybe more I'm not thinking of right now.

**Comment by fosterlynn** [comment]
>oh, i use "event" when talking about event-based programming 

Funny enough, that is a lot closer to the behavior of rea:EconomicEvent than the kind you hold and a lot of people come to....  :wink: 

Time to get out the thesaurus....

**Comment by elf-pavlik** [comment]
> Don't know. People don't tend to use prefixes in any setting that they are not required to do so.

When we speak or write free form text we probably should use term Economic Resource and Economic Event. Still for code snippets and our conversations happening on various online venues, I find `vf: ` prefix even more precise and making it clear that we talk about term defined in Value Flows namespace. Once again, when you say just 'Economic Event', does it also relate to 'Input Plan' or only applies to Observation/Report (former Reality) layer? I think we really should work on self discipline and clearly use terms with `vf:` prefix plus stay generous with YAML (or raw JSON-LD) snippets.

Lately I sometimes use `vf-x:` to suggest that it may fit at some point in `vf:` but we still haven't written down .md page with clear definition and include its formal definition in our OWL based ontology (for use in LOD).

**Comment by bhaugen** [comment]
I am attempting to use prefixes in what I write in VF repos, although sometimes I will introduce terms with a prefix and then leave them off and use the lowercase form for subsequent text, although I could use the prefix always if that works better in the VF context. I am talking about other people who will not be so constrained (as I thought would have been clear).

**Comment by elf-pavlik** [comment]
@bhaugen does *vf:Resource* work for you or you need the explicit 'Economic' even with the `vf:` prefix?

**Comment by bhaugen** [comment]
> does vf:Resource work for you or you need the explicit 'Economic' even with the vf: prefix?

Personally, I prefer the explicit Economic. But I do not want to be the Benevolent Dictator. (I have asked Lynn, if I start acting like some people we know, to shoot me.) I want the gang to take over. I will not block any consensus decisions.

**Comment by fosterlynn** [comment]
Pulling from gitter, just to have it available....

>Pavlik:  i have stronger and stronger impression that REA focuses on stocks (and stock-flows)

Bob: REA is an abstract model. Bill McCarthy never instantiates resources at all. When he wants to know something about resources, he summarizes the event records. He is not developing operational systems.
When I ran into REA, he still thought it was an internal company accounting model.
When I told him it was a general economic model, he immediately got it, but was still not thinking operational systems.
So it has been mostly up to Lynn and me to develop operational REA systems, and we like to instantiate resources.
And give them identifiers. And now a LOD identifier.
But even as an economic model, a resource is a resource to somebody. Somebody who uses it, and somebody who is responsible for it, and they don't need to be the same.
In REA terms, that is some agent.
In general, the agent who is responsible for the resource gets to define it.
If it is a common resource, commons always are managed, they are not free-form, or all the bikes will be gone.
So anyway, an economic resource is not the same as a physical object. It might be a representation of a physical object, but it's the same kind of comparison as the map is not the territory.
If we have community bikes, and one bike is given to another community, the LOD identifier of that bike may change. It may become a different resource.
Economically, it is different, because it is now part of a different community.
But it will still have the same serial number, and still be the same physical object.
If the bike itself was an intelligent robotic bike, and had its own Web identity, and was given to a different community, the bike would announce on its blog that it is now the resource of a different community.
