### ISSUE TITLE
Can you have a zero quantity vf:EconomicResource?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/resource#24]
Depends on what you mean by "have", which I think depends on what you want to do with it.

If you want to use the resource in some way, no.

If you want to refer to a resource that once existed, and want to see its history, yes.

We have discussed how to identify resources in https://github.com/valueflows/resource/issues/13 and https://github.com/valueflows/resource/issues/23

Regardless of which form of identification we use, a vf:EconomicResource will have an IRI if and when some vf:Agent chooses to define it. So it will exist, at least in that way, regardless of its quantity (which could initially be zero, and may be zero again off and on, and it can still exist as an IRI which identifies a vf:EconomicResource that existed in tangible form now and then. And you might be interested the history of its appearances and disappearances from tangible form. 

If a vf:EconomicResource is identified indirectly, for example by vf:EconomicResourceType and location, with a quantity of 100, and then all 100 are consumed, the identification will need to remain, at least for historical reports. If tomorrow 150 of the vf:EconomicResource fitting that indirect identification appears, are they the same vf:EconomicResource?  According to their identifier, they are. 

If the vf:EconomicResource was identified by lot id and location, then when 100 are consumed, and 150 more of the same vf:EconomicResourceType but a different lot id appear in the same location, those will not be the same vf:EconomicResource.

If the vf:EconomicResource was identified by a serial number and location, then its quantity will be 1, and when it is gone, whatever resources show up in the same location tomorrow will be different vf:EconomicResources.

These conclusions may seem paradoxical if you are thinking of a resource as a physical object that you can pick up and move to someplace else. But all we got are electronic representations, and that (above) is all they can do. It's another difference between the map and the territory.

**Comment by elf-pavlik** [comment]
I think it relates to #11 

* I have a stock of 50kg of apples
* You have a stock of 50kg of apples
* We move 50kg of apples from my stock to your stock
* I 'have' an empty stock of apples with no apples in it
* You have stock of 100kg of apples
* We move 50kg of apples from your stock to ..
 * I can merge that 50kg into my old empty stock
 * I can create a new stock out of those 50kg

It can get more interesting if we have hard allocations #22 and multiple stocks of apples which we can split and merge.

**Comment by elf-pavlik** [comment]
> Regardless of which form of identification we use, a vf:EconomicResource will have an IRI if and when some vf:Agent chooses to define it. So it will exist, at least in that way, regardless of its quantity (which could initially be zero, and may be zero again off and on, and it can still exist as an IRI which identifies a vf:EconomicResource that existed in tangible form now and then.

I made PR which proposes vf:Stock #41 which may help with drawing distinction between resources and stocks of resources. I think included example with bicycles comes even more clear that my example above with apples.

* I have a stock of 5 bicycles
* You have a stock of 5 bicycles
* We move 1 bicycle from my stock to your stock
* I have 4 bicycles in my stock (got decremented)
* You have 6 bicycles in your stock (got incremented)
* We moved **a resource** (bicycle with serial nr) between our stocks

If we move 4 more bicycles from my stock to your stock, I will have stock with 0 bicycles. Still I may want to keep that empty stock and it can have information like *maxQuantity* so others know that they can possibly move up to that many bikes to that stock (currently empty one).

**Comment by fosterlynn** [comment]
Per discussion with @elf-pavlik , a vf:Resource can have a zero quantity.  One thing this supports is the ability to plan against a specific resource, not just a type of resource.  So the resource can have zero quantity (it lives on the observation layer), but can have a plan or commitment  for a quantity > 0 that references that resource.

**Comment by elf-pavlik** [comment]
Thank you for capturing it here @fosterlynn, relevant comment in other issue https://github.com/valueflows/resource/issues/14#issuecomment-238354420

I think we can make PR about quantity: 0 resources and close this issue after merging it!
