### ISSUE TITLE
vf:isSubstitutable (rdf:Property) or vf:Substitutable (rdfs:Class)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#25]
https://github.com/valueflows/resource/blob/master/Resource.md#resource-definitions

> vf:isSubstitutable: For a resource type, defines if any resources of that type can be freely substituted for any other resource of that type when used, consumed, traded, etc. For example, "B9R-1-red DLP resin photopolymer" is probably a substitutable resource type. While each resource for a resource type called "English-Spanish translation" is probably not substitutable because each will be a different document.

I assume that _vf:isSubstitutable_ would have definition like (prefix definitions not shown)

``` turtle
vf:isSubstitutable a rdf:Property ;
  rdfs:domain vf:Resource ;
  rdfs:range xsd:boolean .
```

I would like to propose another approach

``` turtle
vf:Substitutable a rdfs:Class .
```

This way we define a set of all substitutable resources and now we can use _rdfs:subClassOf_ to mark any class as included in that set. For example

``` turtle
ex:B9R-1-red_DLP_resin_photopolymer a rdfs:Class ;
  rdfs:subClassOf vf:Resource, vf:Substitutable .
```

Of course some UI might just show something like 'Create new resource type' button (this would mark new class as sub class of vf:Resource) and then new resource type definition UI would have checkbox "is substitutable" which when checked would mark new class also as sub class of vf:Substitutable).

**Comment by bhaugen** [comment]
Fine with me. I think also that substitutable may go with several other properties that I can enumerate at the moment.

**Comment by elf-pavlik** [comment]
We will need to stay patient in exploring where we see it appropriate to use RDFS/OWL to define classes and where we see it appropriate to define instances. In general, whenever we want have instance included in some kind of set, defining a class and relating instance with it through `rdf:type` predicate seems more natural. All *-able categorizations should fit that approach very well.

**Comment by fosterlynn** [comment]
@elf-pavlik  I take your LOD experience as way past mine here.  But I got a question.

>```turtle
ex:B9R-1-red_DLP_resin_photopolymer a rdfs:Class ;
  rdfs:subClassOf vf:Resource, vf:Substitutable .
```

>Of course some UI might just show something like 'Create new resource type' button (this would mark new class as sub class of vf:Resource) and then new resource type definition UI would have checkbox "is substitutable" which when checked would mark new class also as sub class of vf:Substitutable).

Does this mean that we do NOT have a vf:ResourceType?  Only a vf:Resource with a huge number of subclasses?  And the subclasses would live on the web in places like wikidata or say the Sensorica NRP app?  And we would basically define a resource type as a subclass of vf:Resource, just like we did for vf:Agent?  

If so, I'm not necessarily objecting.  I'll take some time and look more closely at gr, schema.org, etc.  I thought that from looking before that they had resource types as instances of things like gf:ProductOrService, but I see that it is either not true or more ambiguous than that.  I'll study what's out there, I know there were recent issue comments on gr and schema.org that I didn't get to looking into before.

Also, where would Unit for a resource type be defined?  Doesn't seem like we could handle that the same as Substitutable?

**Comment by fosterlynn** [comment]
Actually, using Substitutable also does not give people a way to define that for a resource type, which seems like a problem to me.  Somehow, people who develop products (etc) need to have a way to define a bunch of things about them before any actual resources are created, or planned, or anything.

What am I missing?

**Comment by elf-pavlik** [comment]
> Actually, using Substitutable also does not give people a way to define that for a resource type, which seems like a problem to me.

This does it, if we define resource types as instances of rdfs:Class
```turtle
ex:B9R-1-red_DLP_resin_photopolymer a rdfs:Class ;
  rdfs:subClassOf vf:Resource, vf:Substitutable .
```

http://www.productontology.org/#faq1 does it by acting as live proxy to Wikipedia concepts.

> If so, I'm not necessarily objecting. I'll take some time and look more closely at gr, schema.org, etc. I thought that from looking before that they had resource types as instances of things like gf:ProductOrService, but I see that it is either not true or more ambiguous than that. I'll study what's out there, I know there were recent issue comments on gr and schema.org that I didn't get to looking into before.

We should analyse
* [gr:ProductOrService](http://www.heppnetz.de/ontologies/goodrelations/v1#ProductOrService) | https://schema.org/Product
* [gr:Individual](http://www.heppnetz.de/ontologies/goodrelations/v1#Individual | https://schema.org/IndividualProduct)
* [gr:SomeItems](http://www.heppnetz.de/ontologies/goodrelations/v1#SomeItems) | https://schema.org/SomeProducts
* [gr:ProductOrServiceModel](http://www.heppnetz.de/ontologies/goodrelations/v1#ProductOrServiceModel) | https://schema.org/ProductModel

Plus http://wiki.goodrelations-vocabulary.org/Axioms#Product_Models

**Comment by fosterlynn** [comment]
>This does it, if we define resource types as instances of rdfs:Class

Got it, sorry!

**Comment by elf-pavlik** [comment]
> Also, where would Unit for a resource type be defined?

We can NOT expect Resource Type to mandate units. For example:

Resource Type: http://www.productontology.org/doc/Apple.html

If we think about Input/Output and Offer/Request
* amount: 5kg , type: prodont:Apple
* amount: 24pcs, type:prodont:Apple
* amount: 11lb, type:prodont:Apple

I agree that agents might want to define default units, which **they prefer to use** for resources of particular type. Still we can NOT rely on type definition to provide unit which will apply to any instance of that type.

**Comment by bhaugen** [comment]
What @fosterlynn mentioned upthread is fairly critical:
>  Somehow, people who develop products (etc) need to have a way to define a bunch of things about them before any actual resources are created, or planned, or anything.

Is that handled in @elf-pavlik 's proposals? Something like substitutable or serlialized or lot controlled could be rdf classes, but that seems fairly heavyweight for properties that are invented by communities. And I mean ResourceType properties, that will apply to all Resources of a type.

**Comment by fosterlynn** [comment]
>We can NOT expect Resource Type to mandate units

Agreed.

**Comment by fosterlynn** [comment]
>Is that handled in @elf-pavlik 's proposals? Something like substitutable or serlialized or lot controlled could be rdf classes, but that seems fairly heavyweight for properties that are invented by communities. And I mean ResourceType properties, that will apply to all Resources of a type.

This is handled in gr and schema.org by gr:ProductOrServiceModel and schema:ProductModel.  Other than that, things are mushed together quite a bit in those ontologies.  But those ...Model classes have a ton of stuff which we haven't needed yet, dimensions, etc. etc.  But are all part of nrp:ResourceType concept.

I'm still thinking.  Don't know where @elf-pavlik is at, we are doing YAML as the next step.  :)

**Comment by fosterlynn** [comment]
So, the gr model (and schema.org seems to have more recently adopted some of gr's structure) has the following:

gr:ProductOrService as the superclass
-- gr:ProductOrServiceModel (this is the rough equivalent / subset of vf:ResourceType)
-- gr:Individual (this is a resource that is one serialized item)
-- gr:SomeItems (this is a resource that is some unknown group of a type of resource)

The last 2 reference the gr:ProductOrServiceModel, so each of those know about their resource type.

But in this model rea:EconomicResource and rea:EconomicResourceType are subclasses of the same thing. 

Ref. http://www.heppnetz.de/ontologies/goodrelations/goodrelations-UML.png

**Comment by bhaugen** [comment]
When I get time, or when it is desperately needed, I will come up with some test cases that will try to decide if that model would work. (Yes, I know, it probably works in their narrow domain. The VF domain is broader.)

**Comment by elf-pavlik** [comment]
Since taxonomies can have hierarchies with many parents, defining some 'Substitutable' category and marking it as another parent/super of some other category could provide alternative to property *isSubstitutable* more in lines of vf:Substitutable as Class/Category of all the substitutable things.
