### ISSUE TITLE
resource types (and models) which differ by processing stage

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#28]
Example of different generic types
- prodont:Apple
- prodont:Apple_juice
- prodont:Oat
- prodont:Rolled_oats

or https://en.wikipedia.org/wiki/Category:Tomato_products

Same can apply also to product models defined in context of some specific agent (provider)
- bumblebee:apple
- bumblebee:apple-juice

Plus various packaging variants 5kg bag or 50kg bag

**Comment by bhaugen** [comment]
Another angle that is interesting about those examples is if you have some recipes, and somebody wants some prodont:Apple_juice, but you don't have juice but do you do have prodont:Apples, you can crank up the apple press and make juice.
