### ISSUE TITLE
modeling 'Usage' as vf:Resource (similar to vf:Service)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#29]
Based on snippet in https://github.com/valueflows/valueflows/issues/110#issuecomment-220734960 and chat with @fosterlynn I would like to consider to model usage as vf:Resource in similar way as vf:Service.

Example: "One day of using particular bicycle"
- It can go as resource on input to my planned instance of _vf:Transportation_
- I can include it as needed resource in instance of _vf:Request_
- I can transfer rights to it in instance of _vf:Request_

I understand that modelling usage as rea:Event might work in context of _vf:Process_, but can we request events and transfer rights to events?

**Comment by bhaugen** [comment]
I'll comment on those two issues separately:
> I would like to consider to model usage as vf:Resource in similar way as vf:Service.

1. Have we nailed down the model for vf:Service yet?
2. Usage applies to inanimate objects like equipment and facilities (rooms, labs, etc). Services usually involve human labor (maybe in addition to usage of equipment etc, or maybe not).
3. Usage has pretty different treatment in value equations than any other (whatever we are calling Event Types these days). You can get a hint of that in [this doc attempting ot explain NRP value equations](https://docs.google.com/document/d/1hg0q7zNyuM1OM-8OOoZrkCPpB_EUH8YGLLnfoDFopy4/edit?usp=sharing). Look for "Treatment of different event types". To quantify, you need to figure out a use value per unit of use. In the code, it is a separate path with some complications.

'twould be good to return to this question when we nail down vf:Service. I got an email question out to some REA experts, but nobody is responding, so we may need to figure it out ourselves...

**Comment by bhaugen** [comment]
> I understand that modelling usage as rea:Event might work in context of vf:Process, but can we request events and transfer rights to events?

Mlost vf requests or commitments will be requests for rea:EconomicEvents.  A claim is basically a right to an economic event. You can transfer claims. See [factoring receivables](https://en.wikipedia.org/wiki/Factoring_(finance)). I've seen an REA treatment of factoring claims, but it was on a whiteboard and I can't remember all the details. The claims were bundled as a resource.

**Comment by elf-pavlik** [comment]
I think that *Service* and *Usage* have many similarities. Let's look at those 3 similar cases:

* I take a taxi from A to B
* I take a self driving taxi from A to B
* I take a [Car2Go](https://www.car2go.com/) style car from A to B

**Similarties**, let's assume that in all cases we use the same model of car, in second case it just has 'autopilot on'. A to B distance 20km and we take the same route
* We have an instance of *vf:Transportation* (process) from A to B 
* I (most obviously my physical body aspect, not the agent aspect) get picked-up and dropped-off. We can see it as transportation service which goes as input into my working day process.
* Process consumes same amount of electricity, uses the same road
* Car needs to stay maintained regularly, other people do that maintenance.

**Diferences**
* In first case another person drives the car. In second car drives itself, In third case I drive the car.

**Accounting**
Let's say that in all cases I had allocation of 300km of travel before hand and just claimed 20km from that, leaving me with 280km more to claim.

**Comment by fosterlynn** [comment]
I'm thinking about the above example with the cars.  I would like to explore these all being services.  I don't have any conclusions yet, or even any tentative proposals! :)

In NRP, for equipment, we have units and units-of-use on a resource type.  In a process, people can log vf:use of some equipment resource using units-of-use, like hours.  Like https://github.com/valueflows/process/issues/7#issuecomment-221329544.  What if use of the equipment were a service, i.e. a different resource?  I don't see the real difference between this and rental of an apartment, which we have said is a resource different than the apartment, either defined using underlying-resource, or as an agent-resource-relationship.  An open question in my mind: is the difference centered around if the resource is "yours"?  Is it a service if the equipment, car, etc. is not yours?  Is it usage if it is yours?  ("Yours" is defined loosely here, ownership or custodianship or completely under your coordination control, or something like that.) In any case, it does seem to me on a gut level that having units and units-of-use is possibly too hacky a model.

**Comment by elf-pavlik** [comment]
>  An open question in my mind: is the difference centered around if the resource is "yours"? Is it a service if the equipment, car, etc. is not yours? Is it usage if it is yours? ("Yours" is defined loosely here, ownership or custodianship or completely under your coordination control, or something like that.)

I would like to work on a way, to model Process independent from any notion of ownership. Transfer deals with that and for Process it shouldn't matter who owns what. It will matter when you do allocation of resources for some particular process, but at the recipe level and observation, ownership aspects should not come into play for describing the process. Similar as accounting it should stay orthogonal.

**Comment by bhaugen** [comment]
I'm still trying to get everybody to start thinking about mutual coordination and what is required for that, and quit being worried about ownership.

Think of a commons, and management of a commons. Commons need to be managed or they will go to ruin. Use of scarce resources needs to be coordinated. Reciprocity is required in terms of upkeep of resources you use. The time you use a commons resource needs to be accounted for.

The process is different from the usage rea:EconomicEvent anyway. The process knows it needs to use a resource for an estimated timespan. How that resource is managed otherwise is not the process's business.

**Comment by fosterlynn** [comment]
>I would like to work on a way, to model Process independent from any notion of ownership

For sure.  But I took your examples to all involve a Transfer (in addition to one or more processes) because I think a Service has to include a Transfer.  I don't know how to model it, but if someone provides you a service (even the CarToGo is a service I think, because other people are maintaining the car, etc.) then once you have received the service, the transfer has already occurred.  Can't give it back.  On the other hand, if I drive my car somewhere, there is no service and no transfer.

**Comment by fosterlynn** [comment]
@bhaugen to clarify: I'm not disputing the requirement for something like units of use, like for equipment or for an apartment.  Just trying to figure out if the equipment and the apartment are different from each other or not, and if not, why don't we model them the same way, whichever that is.

**Comment by elf-pavlik** [comment]
> even the CarToGo is a service I think, because other people are maintaining the car, etc.
> On the other hand, if I drive my car somewhere, there is no service and no transfer.

What if you live in co-living arrangement and share 3 cars among 10 people? (scheduling software assists you with coordinating that). This goes in direction of [Shared elecric lawnmower](https://github.com/valueflows/valueflows/blob/master/use-cases/shared_electric_lawnmower.md) use case

> Just trying to figure out if the equipment and the apartment are different from each other or not, and if not, why don't we model them the same way, whichever that is.

:+1:

**Comment by elf-pavlik** [comment]
Another common case, also related to renting an apartment, - usage of laundry machines. I know that in some blocks of flats, each flat has a day assigned to use the laundry machine. It belongs to the rental agreement, similar as possible parking place.

**Comment by bhaugen** [comment]
There's two concepts mixed up here: 
* usage as someone's "right" (looking for a better word, but don't have it yet) to use a resource, and
* usage as a record of actual use.

Like, I reserved that 3d printer for tomorrow afternoon (my right to use), and then I used it for 3 hours (my actual use). The actual use is an rea:EconomicEvent. The reservation or right or whatever as yet does not have an agreed-upon vf or REA model.

**Comment by elf-pavlik** [comment]
@bhaugen could you please provide links to some REA examples of describing usage? If possible not from NRP but someone else's work.

**Comment by bhaugen** [comment]
http://valdev.webfactional.com/accounting/resource/411/

It's out there on valdev, you can take it for a spin yourself.

**Comment by elf-pavlik** [comment]
This seems to model usage as service: http://valdev.webfactional.com/accounting/process/793/

Do you have some REA but not NRP examples of usage?

**Comment by bhaugen** [comment]
That's a service package that Lynn created which includes the usage of the 3d printer as part of it.

> Do you have some REA but not NRP examples of usage?

Usage in REA would either be a commitment for the use of (for example) a 3d printer or an economic event that reported some actual usage of the 3d printer.  REA in this case is pretty much the same as NRP.

Services in REA do not have such a well defined model. I asked recently for some help on this, but haven't gotten any responses yet. Will try again.

**Comment by elf-pavlik** [comment]
@fosterlynn could you please explain little more about this instance of nrp:EconomicResource http://valdev.webfactional.com/accounting/resource/434/

**Comment by fosterlynn** [comment]
@elf-pavlik I'm trying to remember the details.  This is from when they community funded a nice 3D printer, at least 10 people contributed.  They were to be paid back over time when people used the printer (except more complicated, depending on if you are an owner, working on a project, working on direct commercial work, etc.).  The technician helping got paid immediately, and $1.50 / hr went into a maintenance fund for the printer.

This was our first experiment with a combinations of exchanges and processes in series from one usage of the printer.  And the rules were quite complicated.  This is some combination of things bundled into a service to get the flow working.

I would advise not worrying about getting into this, it was the first time thinking this type of thing through, and was an improvisation.  The use case is interesting, but what I did with it I don't think is worth thinking about.

**Comment by elf-pavlik** [comment]
I think we have some similarity
* work (rea:EconomicEvent) & service (rea:EconomicResource)
* use (rea:EconomicEvent) & rental service? (rea:EconomicResource)

I think we could look at few more use cases of renting
* bike rental
* car rentalal
* hotel rooms & subletting (also airbnb like and couchsurfing)

We have cases of usage above, but I don't know if we would only model them as rea:EconomicEvent, I see them in many ways also a service rea:EconomicResource.

Each reservation for usage decreases *availability* of reserved resource. We can also transfer our reservations (shares of resource availability). [Access over ownership is the future of consumption](http://www.theguardian.com/sustainable-business/access-over-ownership-future-consumption) IMO that access in many ways seems to fit concept of *economic resource*.

**Comment by bhaugen** [comment]
The actual usage is an rea:EconomicEvent. What is used is an rea:EconomicResource. The reservation for use is an rea:Commitment, or depending on a set of commitments and events, maybe an rea:Claim. As you mention, claims and commitments can be transferred, but I have never done do am not sure of the exact model for doing so, but I think Bill McCarthy is fairly clear on how to do it.

The only concepts that I know are a little fuzzy in REA are services where the service is a bundle of events, and the ontological model for right-to-use, as in rental. I know rights in REA do not have a settled model, and if services do, I don't know it.

**Comment by elf-pavlik** [comment]
Besides the *use* event and *reserve* commitment, I also see distinct aspect of **availability**. Let's say:
* 5 people co-own 3D printer
* each of them has 20% of availability to use it
* they do reservations (commitments) dynamically (first come first served) using a monthly quota
* each of them can transfer the rights to any part of their share of printer availability, this creates a sub quota to use in reservations

Scenario above gives a quite flexible approach to allocating access to the use of that printer. I see it somehow similar to the use case [Peanuts deposited in community storage](https://github.com/valueflows/valueflows/blob/master/use-cases/shares.md#peanuts-deposited-in-community-storage). If we had more perishable product, which we could store for up to one month (short *expiration* date), we would have similar monthly consumption quota for it as in the case of usage of the 3d printer. If you or no one else won't eat it it will rot ~= If you or someone else won't use the printer, your monthly quota will expire. I think this example illustrates that use availability in many ways fits concept of rea:EconomicResource.

**Comment by elf-pavlik** [comment]
After writing some YAML for 'logical stocks' in https://github.com/valueflows/resource/issues/39#issuecomment-239349202 I think we can model *Usage* and *Availability* in similar way.

For example a desk at coworking space may have **Availability**: *Monday-Friday 8AM - 8PM*
Than people in their 'workday' process can add planned **Usage**: *10AM - 2PM on Tuesday, Aug 9th 2016*. Reference it in *vf:Request* addressed at particular coworking space and than receive **vf:Allocation** which would represent booking.

We need to start simple but already keep in mind requirements like *flexibility of allocation*, *periodicity* etc. Just as in transportation one have 'n transfers' (also when filtering searches) one can have 'ok to change desk' for using coworking spaces. Similar to 'respect your seat numbers' in a vehicle or cinema.

Similar should work for reservation of co-living spaces, tables at restaurants. Also overlap in requirements with transportation services. In general we need to describe *availability* with its time aspects and *usage* with its time aspects. Then systems would need to do matching and allocations (scheduling) having some validations to warn if we overbook service or reserve same too for two different processes at the same time.

I'll start describing in YAML examples, planned *usage* and *allocations* as resources. Underlying resource should come handy in those cases.

**Comment by bhaugen** [comment]
Maybe some ideas in this list? [open source room scheduling software](https://duckduckgo.com/?q=room+scheduling+software+open+source&t=hg&ia=web)

**Comment by fosterlynn** [comment]
Some tentative simple yaml to see what Usage as a vf:Resource looks like, ignoring availability for now.  Borrowing the 3d printer use case, snippet to use the printer in a process. 

#### Beginning resources:

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/d8f97d89#stock
'@type': vf:Resource
'vf:model': ord:ORD-FDM-3D-printer
'vf:serialNumber': d8f97d89
'vf:quantity':
  '@type': qudt:QuantityValue
  'qudt:unit': unit:Each
  'qudt:numericValue': 1
```
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/d8f97d89#usage
'@type': vf:UsageResource
'vf:category': sens:EquipmentUsage
'vf:underlyingResource': https://fablab.example/d8f97d89#stock
'qudt:unit': unit:Hour
```

#### Process:

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/818f30f4-c119#process
'@type': vf:Transformation
'skos:note': using the 3d printer
'vf:contextAgent': https://fablab.example/OhioFabLab#agent
'vf:io':
  - '@id': '#input-2'
    '@type': vf:ResourceEvent
    'vf:action': vf:consume
    'vf:eventDate': 2016-08-10
    'vf:resource': https://fablab.example/d8f97d89#usage
    'vf:eventQuantity':
        '@type': qudt:QuantityValue
        'qudt:unit': unit:Hours
        'qudt:numericValue': 2.5
```

Notes/questions:

* Should we use a vf:consume event action?
* I put the unit in the usage resource, but it can more easily be on the resource type (which I think would be the vf:category).  The usage resource doesn't have the same vf:quantity, because that is all about the availability, which is a more complex data structure.

**Comment by elf-pavlik** [comment]
@fosterlynn thank you! I like that YAML 😄 just few minor suggestions

> I put the unit in the usage resource, but it can more easily be on the resource type (which I think would be the vf:category). The usage resource doesn't have the same vf:quantity, because that is all about the availability, which is a more complex data structure.

Two printers of the same type can have different usage patterns. One in the Lab per hour but another one stored in warehouse maybe only per day (someone needs to set it up). Of course we can have two distinct stocks #41 with same 'resource type' but containing different instances. Usage conditions we could define per such stock. I would also use *vf:usageUnit* and not try to reuse *qudt:unit*.

> Should we use a vf:consume event action?

Seems fine to me. When (if) we get to modeling *availability* as stock, such usage will actually decrement it.

> We currently have these subclasses of vf:Resource: MaterialResource, ServiceResource, WorkResource, CurrencyResource. Do we want UsageResource? (or something like that)

Would you like to make PR for it? Besides .md pages for each of those subclasses we should update resource.ttl and VOWL diagram.

**Comment by elf-pavlik** [comment]
Actually your definition looks like a 'resource type' of usage and not the 'resource'
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/d8f97d89#usage
'@type': vf:UsageResource
'vf:category': sens:EquipmentUsage
'vf:underlyingResource': https://fablab.example/d8f97d89#stock
'qudt:unit': unit:Hour
```
On 'plan' layer resource should have at least duration and if already allocated than reference input of a process, on 'observation' layer it must have both - duration and input.

Besides looking at Usage as input of a process, we should also think about process that has it as its output.

**Comment by fosterlynn** [comment]
>Two printers of the same type can have different usage patterns. One in the Lab per hour but another one stored in warehouse maybe only per day (someone needs to set it up). Of course we can have two distinct stocks #41 with same 'resource type' but containing different instances. Usage conditions we could define per such stock.

Yes good case, so let's have it on both.  The case for having a unit on a resource type (model) is for recipes.  And also for when you don't want to have to keep entering it for resources.

**Comment by fosterlynn** [comment]
>Actually your definition looks like a 'resource type' of usage and not the 'resource'
>On 'plan' layer resource should have at least duration and if already allocated than reference input of a process, on 'observation' layer it must have both - duration and input.

This example was meant to be just a vf:Resource, not a plan or commitment or event.  It is a usage resource but not managed by a calendar.  Should we not have an actual vf:Resource in that case?  Just the resource type?  

But I don't think it can be a resource type because it is usage of a specific actual resource.  Hmmmm.  I'm fine not having an actual vf:Resource if we can figure out how to represent that there is usage of a specific item which can be requested, committed to, etc.

**Comment by fosterlynn** [comment]
Further discussion over at https://github.com/valueflows/valueflows/issues/143 for the time-based variety....

**Comment by elf-pavlik** [comment]
Having usage modeled as *vf:TimeBasedResource* do we still need *vf:usership* relationship between agend and the 'underlying resource' of that usage TBR?

**Comment by fosterlynn** [comment]
>Having usage modeled as vf:TimeBasedResource do we still need vf:usership relationship between agend and the 'underlying resource' of that usage TBR?

Can't find vf:usership and can't bring up where it might be, but sounds like we don't need it?

**Comment by elf-pavlik** [comment]
Following example in https://github.com/valueflows/process/issues/22#issuecomment-241164236 and #51 

We can consider *vf:UsageResource* without IPO chain which one can reference in *vf:Transfer*, for example with *vf:recipient* agent <-> resource relationship: 

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/d8f97d89-20160815#usage
'@type': vf:UsageResource
'vf:recipient': https://steve.example/#identity
'vf:start': 2016-08-15
'vf:durationQuantity':
  '@type': qudt:QuantityValue
  'qudt:unit': unit:Day
  'qudt:numericValue': 1
```

**Comment by elf-pavlik** [comment]
Some categories of *vf:UsageResource* may need to capture more quantity with more than one *qudt:QantityValue*, for example usage of a car (or bike) could capture both time (durration) and distance.

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://comove.example/d8f97d89-20160815#usage
'@type': vf:UsageResource
'vf:underlyingResource': https://comove.example/trucks/234012910-12313#resource
'vf:recipient': https://steve.example/#identity
'vf:start': 2016-08-15
'vf:quantity':
  - '@type': qudt:QuantityValue
    'qudt:unit': unit:Hour
    'qudt:numericValue': 6
  - '@type': qudt:QuantityValue
    'qudt:unit': unit:Kilometer
    'qudt:numericValue': 32
```

The *use* event in transportation process, would consume as input that whole resource `https://comove.example/d8f97d89-20160815#usage` and not some quantity of it.

**Comment by elf-pavlik** [comment]
Moving conversation from https://github.com/valueflows/valueflows/issues/133#issuecomment-241263027

> @elf-pavlik
At the same time not providing way to model processes that output work and usage (the 'time based stock'- availability?). 

> @bhaugen 
Inanimate tangible resources that are used in time increments are created like any other tangible resources, as outputs from manufacturing or construction processes, usually measured in Eaches (units of count, not units of use).

> @elf-pavlik
What about the maintenance? Sometimes 'custodian' also needs to contribute some work to make some tool available...

> @bhaugen 
Absolutely! Those are the lovely processes where the same resource is an input and an output. The tool is still an "Each". But the usage processes have reciprocal relationships with the tool and its original acquisition or creation as well as its ongoing maintenance.

If a bike breaks, it's quantity is still an "Each" but its 'time based availability stock' gets `quantity: 0, availableQuantity: 0`. Once the bike gets repaired, it still stays "Each" but its 'time based availability stock' increments `quantity > 0` and people can make reservations once again `which affects the `availableQuantity`. I see the *usage* as related but **distinct** resource from the tool itself. Maybe we miss some kind of 'stewarding process' which outputs the usage availability of tools and to which repair services go as input as well as 'steward'/'custodian' work? In general I see need to give more attention to the [temporal dimension](https://en.wikipedia.org/wiki/Dimension#Time)

**Comment by bhaugen** [comment]
It would also seem possible to define some constraints between the count resource and the related time-based resources so those changes can be automated.

But in general, time-based resources will need to be inventoried on a schedule of whatever granularity. (And we need to select a time ontology so we know how to talk about those timeslots.) If the tool or whatever is the count resource is in for repair, its timeslots do not exist for that timespan. The schedule will have a gap.
