### ISSUE TITLE
Measurements: Quantities, Dimensions, Units

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/resource#3]
[as `valnet` shows](https://github.com/valnet/valuenetwork/blob/master/docs/core_model.txt), we need a way to measure quantities, units, and [kinds](https://github.com/valueflows/resource/issues/2) of things.

previously i dove into [`qudt`](http://www.qudt.org/) and wrote some [json-ld schemas](https://www.npmjs.com/package/schema-jsonld-context) ([Quantity](https://github.com/valueflows/valueflows/blob/4119b18541f0b4aa9017583251c3067b4b6734be/vocab/Quantity.js), [Unit](https://github.com/valueflows/valueflows/blob/4119b18541f0b4aa9017583251c3067b4b6734be/vocab/Unit.js), [Kind](https://github.com/valueflows/valueflows/blob/4119b18541f0b4aa9017583251c3067b4b6734be/vocab/Kind.js))

**Comment by elf-pavlik** [comment]
another relevant vocab: https://iotdb.org/pub/iot-unit.html

**Comment by ahdinosaur** [comment]
use cases:

- 50.4 kg of flour
- 30 crates of 50 kg apples per crate
- 10 kWhr of electricity
- 12 L of water
- $100 per hour

**Comment by ahdinosaur** [comment]
using [QUDT](https://collab.firelab.org/software/projects/39/wiki/QUDT)

50.4 kg of flour

```yml
'@context':
  qudt: http://qudt.org/1.1/schema/qudt#
  unit: http://qudt.org/1.1/schema/unit#
  vf: https://w3id.org/valueflows/
  ex: https://example.org/
'@type': ex:Flour
'qudt:quantityValue':
  '@type': qudt:QuantityValue
  'qudt:numericValue': 50.4
  'qudt:unit': unit:Kilogram
```

**Comment by ahdinosaur** [comment]
30 crates of 50 kg apples per crate

``yml
'@context':
  owl: http://www.w3.org/2002/07/owl#
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  qudt: http://qudt.org/1.1/schema/qudt#
  unit: http://qudt.org/1.1/schema/unit#
  vf: https://w3id.org/valueflows/
  ex: https://example.org/
'@type':
  '@id': ex:resourceTypes/crate-of-apples
  'rdfs:subclassOf': vf:Resource
  'vf:label': delicious apples from local growing co-op
  'qudt:quantityValue':
    '@type': qudt:QuantityValue
    'qudt:numericValue: 50
    'qudt:unit': unit:Kilogram
'qudt:quantityValue':
  '@type': qudt:QuantityValue
  'qudt:numericValue': 30
  'qudt:unit': unit:Unitless
```

**Comment by bhaugen** [comment]
Units of measure is one of the several concepts that I think we should delegate to some other vocab, and not try to define it ourselves.

Location is probably another. Likewise time.

**Comment by elf-pavlik** [comment]
@ahdinosaur AWESOME thanks a lot!

do you use valid CSON or YAML? it doesn't validate in http://www.coffeelint.org/

**Comment by fosterlynn** [comment]
@ahdinosaur awesome indeed!

**Comment by gcassel** [comment]
>Units of measure is one of the several concepts that I think we should delegate to some other vocab, and not try to define it ourselves.

I don't think we can (or should) try to control the development of all VF-related vocabs, but perhaps it'd be good to define desired modules/components/ plug-ins, and to link any viable efforts which attempt to satisfy the interface specifications?

**Comment by bhaugen** [comment]
Sorry I wasn't clear. That's what I meant: use something like qudt for units, but specify one. Stick to a minimal core ourselves.

Better?

**Comment by ahdinosaur** [comment]
@elf-pavlik this is YAML, i find it easier for sharing ideas than JSON.

**Comment by elf-pavlik** [comment]
@ahdinosaur would you like to create a use case out of the crate with 50kg of apples in it?
I think we may need to introduce concept of package. Some apples providers might actually want to also keep track on their wooden crates and rent them out based on some deposit.

**Comment by bhaugen** [comment]
We will need packages, and package sizes (how many per package) depends on resource type, and sometimes resource type details (large broccoli heads vs medium vs small, for example).

**Comment by elf-pavlik** [comment]
Foodsoft has some nice UI for dealing with boxing issues and using tolerances on equivalent of *vf:Request*, which assist filling up the boxes - https://vimeo.com/145927538 (starts ~5:15)

**Comment by elf-pavlik** [comment]
I'll make PR which clarifies that for vf:quantity we use *qudt* + in Resource.ttl
```ttl
vf:quantity
  a rdf:Property ;
  rdfs:range qudt:QantityValue .
```

**Comment by elf-pavlik** [comment]
Looking at http://www.qudt.org/ I don't find *unit:Each* which somehow sneaked into many of our YAML snippets. We should find appropriate unit to replace it and update all the snippets...

**Comment by fosterlynn** [comment]
Wow they have a serious list of units.  They don't have the non-metric measurements either.  Makes sense, it is a scientific vocab.  Looks like Each is in their "dimensionless" unit - counts, etc - but not explicitly anywhere I saw, by any name.

There will be other units of measure that people will want to define besides Each.  Like Words (the translator folks like this one).  And it looks like they do allow people to define additional units.

From our walk discussion this morning - although I'm a big fan of letting people define their own config data (types, etc.), in the case of units, it makes sense to have as much already defined as possible because there will be a big need to communicate in widely understandable units.  Wondering if we can easily support more than one vocabulary for the measurement piece, by using vf definitions with rdfs:range into multiple vocabs? ( @elf-pavlik )  Qudt seems really good for scientific stuff, which some people will want.  I'll do a bit of research into other more commercial measurement vocabs.

**Comment by fosterlynn** [comment]
Another note from @bhaugen from our walk - there are also needs for things like cases, 6-pack of beer, etc., that are a bit more complicated.

**Comment by elf-pavlik** [comment]
> there are also needs for things like cases, 6-pack of beer, etc., that are a bit more complicated. 

Sounds similar to Mikey's example above with
> 30 crates of 50 kg apples per crate

6-pack groups 6 beers into a new grouped resource, later we have 'each' number of 6-packs

At the same time we need a way to say that bottle or can of beer combines the packaging and certain Volume of beer. Packaging later needs to get returned or recycled so we need to have a way to track it as any other economic resource.

**Comment by elf-pavlik** [comment]
https://schema.org/TypeAndQuantityNode recommends 
> The unit of measurement given using the UN/CEFACT Common Code (3 characters) or a URL

https://www.unece.org/fileadmin/DAM/cefact/recommendations/rec20/rec20_rev3_Annex3e.pdf

**Comment by bhaugen** [comment]
That spec is so baroque that I wonder whose ERP or ecommerce software it came from. (I've participated in several standards groups and that was often the source: somebody wants to get their stuff baked into a standard.) This says it was derived from GoodRelations. But [gr:TypeAndQuantityNode](http://purl.org/goodrelations/v1#TypeAndQuantityNode) is not that elaborate.

**Comment by elf-pavlik** [comment]
http://www.heppnetz.de/ontologies/goodrelations/v1#hasUnitOfMeasurement

> The unit of measurement for a gr:QuantitativeValue, a gr:UnitPriceSpecification, or a gr:TypeAndQuantityNode given using the UN/CEFACT Common Code (3 characters).

I don't say we should recommend it, but at least stay aware of it and if we find people publishing data using it we could suggest way for converting.

**Comment by bhaugen** [comment]
I'm not against it, especially the GoodRelations version. I was just harking back to my experiences with corporate agendas in standards orgs. And I still like standards orgs, despite all that.
