### ISSUE TITLE
Resource stage

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#30]
@fosterlynn wrote in Resource.md

> Resource stage (where it is based on the last process or transfer made for the same resource in a work flow situation, like Translation@translated, Translation@edited, Translation@proofread).

I'll link to this issue below that section.

IMO we may need some construct for the workflow itself which may connect resource to a stage of that particular workflow.

**Comment by bhaugen** [comment]
* [Loose coupling vs tight coupling](https://github.com/valnet/valuenetwork/wiki/Loose-coupling-vs-tight-coupling,-or,-direct-process-dependencies-vs-resource-flows)
* [Specifically in workflow tools](http://bionics.it/posts/workflows-dataflow-not-task-deps)

**Comment by fosterlynn** [comment]
See also https://github.com/valueflows/process/issues/12

**Comment by elf-pavlik** [comment]
See my comment nr 3 in https://github.com/valueflows/process/issues/12#issuecomment-221095085

We can use backlink to find the output and than the process. It looks that we don't need anything else than using that backlink (JSON-LD `@reverse`)

**Comment by elf-pavlik** [comment]
> @elf-pavlik: resourceClass property? values of what type would appear here?

> @fosterlynn: We added that to say something like "carrot" so that all resource types that were carrots but had some transformation through workflow processes could know they were the same class of thing. Haven't used it much. For a while in DHEN we had Catnip Fresh and Catnip Dry as 2 resource types, that both were class Catnip.

**Comment by fosterlynn** [comment]
>@elf-pavlik: resourceClass property? values of what type would appear here?

>@fosterlynn: We added that to say something like "carrot" so that all resource types that were carrots but had some transformation through workflow processes could know they were the same class of thing. Haven't used it much. For a while in DHEN we had Catnip Fresh and Catnip Dry as 2 resource types, that both were class Catnip.

Yeah, we used it because DHEN has a generic recipe for the steps herbs go through, because they are all basically the same and who wants to define 200 recipes that are the same.  But then because we had a generic recipe, defined on the Resource Type "Herb", which is parent resource type to all the herb resource types, we needed to know that "fresh catnip" and "dried catnip" could be used for "fresh herb" and "dried herb" in the recipe.

This is just a further explanation, not making any proposals.

**Comment by elf-pavlik** [comment]
I think we need to work on it together with cases where you define different resource type based on how you package them. For example carrots 5kg in a bag or 50kg in a crate - same carrots from the same field stored in the same stock just package differently.
