### ISSUE TITLE
YAML examples for vf:underlyingResource

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#31]
from Resource.md

> **vf:underlyingResource**: A more concrete resource which a resource is based upon.  For example, a resource which defines the rental of an apartment has the apartment itself as its underlying resource.  

We need to add snippets to illustrate it. Two instances of _vf:Resource_ connected with _vf:underlyingResource_
- an instance of _vf:Resource_ representing "the rental of an apartment"
- an instance of _vf:Resource_ representing "apartment itself"

I think we should base it on and link to [apartments use case](https://github.com/valueflows/valueflows/blob/master/use-cases/apartments.md)

**Comment by fosterlynn** [comment]
Also: https://github.com/valueflows/process/issues/12

**Comment by elf-pavlik** [comment]
@fosterlynn I understand that currently we only use this property to relate instance of *vf:UsageResource* to instance of *vf:MaterialResource*?

**Comment by fosterlynn** [comment]
>@fosterlynn I understand that currently we only use this property to relate instance of vf:UsageResource to instance of vf:MaterialResource?

Another possible use that has come up is to relate a bank account that exists in a bank with "virtual accounts" that are defined by a group to manage funds within their bank account.  All vf:Resources I believe. Also related to currency, Faircoin has for example wallets and addresses, both of which are vf:Resources.  Addresses would have the wallet as a vf:underlyingResource.

Might be others....  ??  I don't think we should restrict, at least yet.

**Comment by pmackay** [comment]
I put a question in Gitter related to this, could `underlyingResource` cover the idea of `infrastructureResource` I suggested, e.g. factories and tools needed to make bikes?

**Comment by fosterlynn** [comment]
@pmackay that should be handled by the recipe.  The recipe will provide a vf:action of "use" which can refer to space, tools, equipment, etc.  In general, the recipe should take care of defining any type of input needed to make something.  (If it doesn't, we can fix it there.) 

We haven't spent much time on it yet in VF, but here's probably way more than you want to know in terms of the ideas and structures we can start with.... :)  https://speakerdeck.com/mikorizal/5-nrp-recipe-concepts-and-tutorial
