### ISSUE TITLE
bind location to another Resource

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#35]
In cases where resource stays on vehicle we could have another property e.g _vf:locationBoundTo_
Based on #34

**Comment by fosterlynn** [comment]
Is it enough that the resource has "disappeared" into a process?  The truck has done the same.  It will come out on the other end of the process.

**Comment by bhaugen** [comment]
We can tell that a resource is on a vehicle if it has experienced a pickup event which was an input to the transportation process. The resource has not really disappeared, it is now part of the process (on the vehicle), until it is dropped off.

The transportation process may have a route. If it is a [less-than-truckload shipping process](https://github.com/valueflows/valueflows/blob/master/use-cases/shipping.md#less-than-truckload-shipping-ltl), it may be a complex route.

**Comment by elf-pavlik** [comment]
> We can tell that a resource is on a vehicle if it has experienced a pickup event which was an input to the transportation process.

👍 looks like events with *load* & *unload* actions could change *vf:locationBoundTo* (or one can just compute it dynamically on demand)
