### ISSUE TITLE
shares and 'logical stocks' of material resources

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#39]
I would like to discuss it based on [Shares: Peanuts deposited in community storage](https://github.com/valueflows/valueflows/blob/master/use-cases/shares.md) use case

> 1. Community of 20 people produced 1000kg of peanuts in one season
> 2. They allocated 200kg to their community kitchen
> 3. They distributed shares to the remaining 800kg using [resource distribution algorithm](https://github.com/valueflows/valueflows/issues/120#issuecomment-217671421)
> 4. All the peanuts stay stored in the same cellar
> 5. Inventory management system keeps track on the allocations
>    - 1 allocation of 200kg community kitchen
>    - 20 allocations adding up together to 800kg
> 6. Each person has a claim for her/his share of peanuts in one's own independent data space
> 7. People can transfer those shares to each
> 8. When someone requests donation of peanuts, shareholders can meet that requests by combining the total weight from any combination of fractions of their shares
### Agents

Let's just focus on 3 people, where one of them also manages the community kitchen:

``` yaml
'@context': https://w3id.org/valueflows/v1
'@graph':

  - '@id': wendy:identity
    '@type': foaf:Person

  - '@id': matthew:identity
    '@type': foaf:Person

  - '@id': joel:identity
    '@type': foaf:Person
    'skos:note': Joel manages community kitchen
```
#### Physical

``` yaml
'@context': https://w3id.org/valueflows/v1
'@graph':

  - '@id': commune:peanuts-2016
    '@type':
      - vf:MaterialResource
      - prodont:Peanut
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 1000
    'vf:currentLocation': commune:big-cellar
```
#### Virtual

``` yaml
'@context':
 - https://w3id.org/valueflows/v1
 - https://w3id.org/role/
'@graph':

  - '@id': commune:kitchens-peanuts-2016
    '@type':
      - vf:MaterialResource
      - prodont:Peanut
    'vf:partOf': commune:peanuts-2016
    'role:owner': commune:identity
    'role:custodian': joel:identity
    'skos:note': For use in community kitchen
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 200

  - '@id': commune:joels-peanuts-2016
    '@type':
      - vf:MaterialResource
      - prodont:Peanut
    'vf:partOf': commune:peanuts-2016
    'role:owner': joel:identity
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 40

  - '@id': commune:wendys-peanuts-2016
    '@type':
      - vf:MaterialResource
      - prodont:Peanut
    'vf:partOf': commune:peanuts-2016
    'role:owner': wendy:identity
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 70

  - '@id': commune:matthews-peanuts-2016
    '@type':
      - vf:MaterialResource
      - prodont:Peanut
    'vf:partOf': commune:peanuts-2016
    'role:owner': matthew:identity
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 15
```

**Comment by fosterlynn** [comment]
I like this treatment, "part-of".   

At some point, I'm curious to see how this compares with the agent-resource-relationship (with vf:quantities on them).  And the "underlying-resource", which would be very similar to the above.

**Comment by elf-pavlik** [comment]
I see it related to my comment here https://github.com/valueflows/exchange/issues/6#issuecomment-214384889 The 'virtual stocks' seem more appropriate for 'earmarked stocks' and sharing control over resources in them. As usual we may need to write more YAML and compare it side by side.

**Comment by bhaugen** [comment]
Earmarked stocks reminds me of shared kitchens where people put their names on batches of food. Do they say "dibs" in Europe or Mexico? If not, what's the equivalent of saying "I get that and you don't"?

**Comment by fosterlynn** [comment]
@elf-pavlik actually I missed the "virtual" part of your suggestion (which I see now in the heading).  Because you have 

```yaml
    '@id': commune:kitchens-peanuts-2016
    '@type':
      - vf:MaterialResource
      - prodont:Peanut
    'vf:partOf': commune:peanuts-2016
```

which seems like it is modeled as a material resource, but part of another material resource.

Do you mean it to be "virtual" or "material"?  (Either way might be a valid model.)

**Comment by elf-pavlik** [comment]
We have material resource (actual peanuts) but virtual stock of them. They all physically stay a part of `commune:peanuts-2016`. so if someone doesn't pay attention to 'vf:partOf' and would add all the peanuts together, would double count them in that case.

**Comment by elf-pavlik** [comment]
I'll not updates inline so we can see how it evolves, we might switch to gist or even our github repos to keep revisions of examples in more managable way.

For agent <-> resource relationship I use binary version, we could also use n-ary whenever we need additional information about that relationship.

### Resources

#### Physical


```yaml
'@context': https://w3id.org/valueflows/v1
'@graph':

  - '@id': commune:peanuts-2016#resource
    '@type': vf:MaterialResource
    'vf:category': prodont:Peanut
    'vf:currentLocation': commune:big-cellar#place
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 1000
    '@reverse':
      'vf:custody': joel:identity#person
```

#### Virtual

```yaml
'@context': https://w3id.org/valueflows/v1
'@graph':

  - '@id': commune:kitchens-peanuts-2016#resource
    '@type': vf:LogicalResource
    'vf:partitionOn': commune:peanuts-2016#resource
    'skos:note': For use in community kitchen
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 200
    '@reverse':
      'vf:ownership': commune:identity#group
      'vf:custody': joel:identity#person

  - '@id': commune:joels-peanuts-2016#resource
    '@type': vf:LogicalResource
    'vf:partitionOn': commune:peanuts-2016#resource
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 40
    '@reverse':
      'vf:ownership': joel:identity#person

  - '@id': commune:wendys-peanuts-2016#resource
    '@type': vf:LogicalResource
    'vf:partitionOn': commune:peanuts-2016#resource
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 70
    '@reverse':
      'vf:ownership': wendy:identity#person

  - '@id': commune:matthews-peanuts-2016#resource
    '@type': vf:LogicalResource
    'vf:partitionOn': commune:peanuts-2016#resource
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 15
    '@reverse':
      'vf:owhership': matthew:identity#person
```

Matthew wants to contribute 30kg of peanut butter cookies for planned charity event. We can see events as processes with input and outputs - they consume resources, sometimes produce some waste, use equipment and require work.

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': commune:charity-event#process
'@type': vf:Transformation
```

Matthew creates new quantity: 0 resource for planned cookies, sets plannedQuantity: 30kg and 'earmark' them as *vf:consume* input for that planned charity event. I use *vf:Allocation* as more specific than *vf:InputOrOutput*. Similar to rea:Commitment but specifying an instance of particular resource not just type it should have.

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': commune:pb-cookies-for-charity-event#resource
'@type': vf:LogicalResource
'vf:partitionOn': commune:peanuts-2016#resource
'vf:quantity':
  '@type': qudt:QuantityValue
  'qudt:unit': unit:Kilogram
   'qudt:numericValue': 0
'vf:expectedQuantity':
  '@type': qudt:QuantityValue
  'qudt:unit': unit:Kilogram
  'qudt:numericValue': 30
'@reverse':
   'vf:owhership': matthew:identity#person
  'vf:resource':
    '@id': commune:charity-event#input-10
    '@type': vf:Allocation
    'vf:action': vf:consume
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 30
    '@reverse':
      'vf:io': commune:charity-event#process
```

I'll repeat process with that allocation of planned resource, just to clarify those `@reverse` links. Please notice that amount that event plans to consume equals 'expected quantity' of that logical resource allocated for consumption in that event.

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': commune:charity-event#process
'@type': vf:Transformation
'vf:io': 
  - '@id': commune:charity-event#input-10
    '@type': vf:Allocation
    'vf:action': vf:consume
    'vf:resource': commune:pb-cookies-for-charity-event#resource
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 30
```

and starts planning a new process *PB cookies for charity event*, based on some recipe, with input plan which just specifies *vf:consume* requirement: '10kg of peanuts' but output plan already references stock created to contain the future output of that process

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': commune:process-to-make-charity-cookies#process
'@type': vf:Transformation
'vf:io':
  - '@id': '#input-1'
    '@type': vf:InputOrOutput
    'vf:action': vf:consume
    'vf:resource': 
      '@type': vf:MaterialResource
      'vf:category': prodont:Peanut
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 10
  - '@id': '#output-1'
    '@type': vf:Allocation
    'vf:action': vf:create
    'vf:resource': commune:pb-cookies-for-charity-event#resource
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 30
```

Than he creates new 'logical stock' for the needed peanuts it with quantity: 0 and expectedQuantity: 10, based on planned input of the process

```yaml
'@context': https://w3id.org/valueflows/v1
'@graph':

  - '@id': commune:peanuts-for-charity-cookies#resource
    '@type': vf:LogicalResource
    'vf:partitionOn': commune:peanuts-2016#resource
    'skos:note': For use in community kitchen
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 0
    'vf:expectedQuantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 30
    '@reverse':
      'vf:ownership': matthew:identity#group
```

And updates process input to reference that resource, *vf:InputOrOutput* changes to *vf:Allocation*. **Actually similar to events we should 'replace' it with allocations since in more complicated scenarios we can have multiple allocations to satisfy single 'input plans' (similar for outputs)**
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': commune:process-to-make-charity-cookies#process
'@type': vf:Transformation
'vf:io':
  - '@id': '#input-1'
    '@type': vf:Allocation
    'vf:action': vf:consume
    'vf:resource': commune:peanuts-for-charity-cookies#resource
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 10
  - '@id': '#output-1' # ...
```

Since he owns some peanuts himself, he makes a process *vf:LogicalOperation* to move some peanuts to that allocated resource. It has no plan and just creates events.

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': commune:process-to-make-charity-cookies#process
'@type': vf:Transformation
'vf:io':
  - '@id': '#input-1'
    '@type': vf:ResourceEvent
    'vf:action': vf:outflow
    'vf:resource': commune:matthews-peanuts-2016#resource
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 2
  - '@id': '#output-1'
    '@type': vf:ResourceEvent
    'vf:action': vf:inflow
    'vf:resource': commune:peanuts-for-charity-cookies#resource
    'vf:amount':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 2
```

this way we get first 2kg of peanuts needed to make cookies for the charity event \o/

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': commune:pb-cookies-for-charity-event#resource
'@type': vf:LogicalResource
'vf:partitionOn': commune:peanuts-2016#resource
'vf:quantity':
  '@type': qudt:QuantityValue
  'qudt:unit': unit:Kilogram
   'qudt:numericValue': 2
'vf:expectedQuantity':
  '@type': qudt:QuantityValue
  'qudt:unit': unit:Kilogram
  'qudt:numericValue': 30
  '@reverse':
    'vf:owhership': matthew:identity#person
    'vf:resource':
      '@id': commune:charity-event#input-10
      '@type': vf:Allocation
      'vf:action': vf:consume
      'vf:amount':
        '@type': qudt:QuantityValue
        'qudt:unit': unit:Kilogram
        'qudt:numericValue': 30
      '@reverse':
        'vf:io': commune:charity-event#process
```

BTW since he has 'vf:ownership' relation with both 'logical resources' we don't have any *vf:Transfer* in this case!

Matthew now starts [Crowdfunding in-kind](https://github.com/valueflows/valueflows/blob/master/use-cases/crowdfunding-in-kind.md) campaign. Other people make logical operations to donate some of their peanuts to that 'earmarked' resource - in that case ownership changes so we will have some transfers. I'll try add some more YAML tomorrow morning or on Sunday!

**Comment by fosterlynn** [comment]
>For agent <-> resource relationship I use binary version, we could also use n-ary whenever we need additional information about that relationship.

I think binary is fine for now because all the history is in the events that affected it - dates, etc.

**Comment by fosterlynn** [comment]
@elf-pavlik question: Can we just use the vf:contains for this use case (of logical parts of a resource) instead of vf:partitionOn?  Main difference is you can't point to which peanuts exactly are any particular person's, where each bike is identified clearly.  But you could easily take out the "logical resource" by measuring it out and removing it.  So the contained resources seem as real as the bikes to me.  

Just trying to keep it as simple as possible, can you think of any situation where there would be implications to calling both of those vf:contains?  Or vf:partOf, whichever direction seems best.

**Comment by elf-pavlik** [comment]
I think we could use *vf:contains* for both. In both cases (distinct bike or any 5kg of) we need a 'stock operation' type of a process to split/extract it from the stock which contains it. I think we should also think about [hard vs. soft allocations](https://github.com/valueflows/resource/issues/22) since what we discuss here seems very relevant to that topic.

**Comment by fosterlynn** [comment]
>I think we could use vf:contains for both. 

:+1: 

>In both cases (distinct bike or any 5kg of) we need a 'stock operation' type of a process to split/extract it from the stock which contains it.

We should support split or no split, depending on if people want hard or soft allocations, true?    But for a split, yes, we need another one of those minimal event types, or maybe the same one, if we use vf:out, vf:in?

**Comment by fosterlynn** [comment]
I would like to propose that we use vf:contains and vf:containedIn to document this scenario, which covers a stock of a material or non-material resource, parts of which are "owned" (or possibly other relationship) by separate agents.  Like the peanuts in this issue.  Would also apply to a bank account split into virtual accounts for different agents.  Both the container and the contained would be vf:Resources.  It is possible we could use this pattern for other rights than ownership, but for now, the proposal just covers ownership.

Parallel proposal: We use vf:underlyingResource for the scenario where we have separate rights that want to be treated as a resource themselves.  So an apartment is a vf:Resource.  Rental rights to the apartment are also a vf:Resource (maybe by date? not sure).  The rental rights resource references the apartment resource as its vf:underlyingResource.

I still see a place for the agent-resource relationship, although it can be derived from the events affecting the resources too.  But this precludes having agent-resource relationships that split up the resource.  In other words, we wouldn't support having say 2 owners of one resource with amounts or percentages on the agent-resource relationship.  There would have to be 2 resources in this case, contained in the original resource.

P.S. I'm not all tied up into the actual terms, but would be happy to settle on some as part of the proposal.

**Comment by elf-pavlik** [comment]
I think we may need some kind of 'rights' with 'underlyingResource' to support divisible and indivisible resources. We also need to stay careful with having 'rights' as resources since it could lead to 'rights to rights'. Actually solid has bit of that dilemma with ACL for ACLs themselves.

**Comment by fosterlynn** [comment]
>I think we may need some kind of 'rights' with 'underlyingResource' to support divisible and indivisible resources

I was thinking that 'underlyingResource' wouldn't care about divisible, it would be some sort of rights to the whole resource.  We would use 'contains' for divided resources. 

Or maybe I don't get it, do you have an example?

**Comment by elf-pavlik** [comment]
5 people have shared ownership over particular resource - even 20% each
* 200kg of peanuts
* 3D printer

While in case of 200kg peanuts 'divisible' resource we can make virtual resources/'logical partitions' 40kg each and say each agent owns that whole virtual resource/'logical partition'. We can't do the same for 3D printer, not 'divisible' resource. Modeling those 'shares' as 'ownership rights' with underlying resource might work for both 'divisible' and not 'divisible' resources.

**Comment by fosterlynn** [comment]
Good example with the 3d printer, thanks @elf-pavlik .  Are you suggesting we don't use vf:contains at all, and just use vf:underlyingResource?

But then there is the example of the stock of serialized bikes.  These don't really want to be rights to an underlying resource.  They want to be a material resource in their own right.

How about for indivisible, like the 3Dprinter, the shares are rights to an underlying resource; divisible we use contains?  The 3D printer doesn't really have "ownership" of the printer, because nobody with a 20% share can sell the 3D printer, for example.  They can only transfer their share.  So the rights of 20% "ownership" of this indivisible resource are more complicated than "ownership" == all rights.  They don't own the printer, they own a share.

So I think we still want both "contains" and "underlyingResource"?  Do you think so?

**Comment by elf-pavlik** [comment]
do we have *rights* which don't map to 'Action verbs'? https://github.com/valueflows/valueflows/issues/124#issuecomment-279267155

i think we can describe rights in similar way to ACL in https://github.com/solid/web-access-control-spec#modes-of-access
> The acl:mode predicate denotes a class of operations that the agents can perform on a resource.

which looks very much like our 'action verbs'

and yes, it looks that no one of those agents who have 20% of shares *owns* the printer - can take action with any possible for that resource 'verb'

> So I think we still want both "contains" and "underlyingResource"? Do you think so?

i think we may need both, but let's keep looking at our use cases
