### ISSUE TITLE
grid resources (water, hot water, gas, electricity, gray water etc.)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#42]
In [Porridge preparation](https://github.com/valueflows/valueflows/blob/master/use-cases/porridge-preparation.md) i use _tap water_ and _natural gas_ - both come from the municipality grid.

We need a way to describe such resources, they behave differently than conventional local stocks. One may also have quotas for usage of grid resources.

**Comment by fosterlynn** [comment]
I did a consulting gig at a gas utility around 2000.  They had a lot of ways of "counting" gas, but I'm guessing that your gas utility charges you on the bill using some volume measure, and probably water too.  But whatever it is, there will be a vf:Transfer there, and they pick the unit, whether a volume unit or BTUs or whatever. So in some ways, it actually isn't different from 100 widgets.   

You don't in practice have a way of measuring per breakfast prep.  That is why people use "overhead" expenses, and treat them differently. They need to get accounted for, but it is usually not worth it to account too specifically, you would have to estimate or measure. 

Anyhow, good use case.

**Comment by fosterlynn** [comment]
P.S.  As an aside, when I did this work, gas had just been de-regulated in the US, and Enron was the most admired company in the industry.  It was a great lesson in capitalism - companies would buy and sell gas at a point in the pipeline just virtually.  You could have 10 sales of some amount of gas at a point, with nobody actually taking possession, it was all speculation.  Ridiculous waste of productive time.

**Comment by elf-pavlik** [comment]
Does it mean that

1) for grid resources we can model the grid as single instance of rea:EconomicResource with huuuuuuuuge quantity.
2) even that another agent owns that resource, i can have *vf:consume* events directly on it, how than we connect it with *vf:Transfer* and *vf:Intent* ?

In case of electric grid, often multiple providers share the same physical grid and they just have 'virtual stocks' of electricity in it. As consumer I connect to that physical grid but I consume from a 'virtual stock' of provider which I have contract with.

If someone wanted to do 'prepaid' grid resources, as in mobile networks, we would have transfer of some quota 'virtual stock' on which I would have *vf:consume* events.

**Comment by fosterlynn** [comment]
>1) for grid resources we can model the grid as single instance of rea:EconomicResource with huuuuuuuuge quantity.

I'm not sure why anyone would want to do that.  Probably agent is part of the identifier of those resources, and probably some kind of location.

>2) even that another agent owns that resource, i can have vf:consume events directly on it, how than we connect it with vf:Transfer and vf:Intent ?

I should have mentioned that whenever someone says that there is some quantity of gas, it is metered.  So it is measured at some point, either on the pipeline for the big dudes, or just the meter on your house.  So there does end up being some real quantity of gas, even though it may not be the same exact molecules as when it is metered another place in the pipeline.  But it is a substitutable resource, so nobody cares.

When you are using gas for your stove, it is gas that is metered as it goes into your house.  Before that it is owned by the utility, now it seems to me it is owned by you.  There is a vf:Transfer in there somewhere.  I don't know how we want to think about the fact that you are billed monthly after you use the gas.  But I'm pretty sure that when you have used the gas (it has flowed past the meter), you owe for it even though no piece of paper has been issued.

I guess I wouldn't make it harder than it actually is.  There is an exchange (2 reciprocal transfers) every month between you and your utility company.  You used that amount of gas during the month.  If you want to know how much you used for the porridge this morning, you would have to meter it.  But there are in fact a lot of "overhead" expenses for anyone or any group.  You have to decide how to account for them, but there aren't many circumstances where people will try to break down something that would just have to be estimated.

I don't know how you want to think about Intents for utilities like gas or water.  Maybe there is a request to turn on the utilities when you move into a house?  You tell them who you are so they know who to bill?

**Comment by elf-pavlik** [comment]
> I don't know how you want to think about Intents for utilities like gas or water. Maybe there is a request to turn on the utilities when you move into a house? You tell them who you are so they know who to bill?

instances of *vf:Request* with periodicity - one month
* tap water 1.5 m3
* gas 2 m3
* electricity 100 kWH

where multiple providers share a grid, one can get offers from various ones and choose who to sign contract with and with who manage transfers of resources and often reciprocal transfers of some other resources - eg. some peanuts to the person who feeds grid from rooftop solar panels and acts as one of the providers i choose to consume from

>  If you want to know how much you used for the porridge this morning, you would have to meter it. But there are in fact a lot of "overhead" expenses for anyone or any group.

If in a household, I would have equivalent of https://openenergymonitor.org for gas I could pretty easily capture consumption. When I cook porridge I don't cook anything else so it makes it pretty straight forward. I think technology for meters and sensors will continue to improve and make such readings even easier. I could also calculate it based on time and settings of the burner.

No matter how we measure it, I think we might want to have a way to describe consumption of grid resources. No matter if one has 'you owe for what you have used' or 'prepaid' agreement on access to them.

BTW I don't expect that we give priority to this issue or close it very soon. Maybe someone will show up and make PR for how to handle it.
