### ISSUE TITLE
perishable resources

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#43]
I think stock of perishable resources need some kind of 'first in first out' management. Or each 'LOT' has an expiration date and it gets managed as separate stock? This gives multiple stocks of the same type at same location.

**Comment by bhaugen** [comment]
Perishable resources are always lot-controlled and have expiration dates.
> This gives multiple stocks of the same type at same location.

Yes. But it seems like a stock as you are using the word in that paragraph is just an rea:EconomicResource. What's the difference, and the need for a new concept? Or do you think of it as a subtype of resources that do not have individual IDs like serial numbers? (That is, back to your earlier distinctions, are indirectly identified?)

**Comment by elf-pavlik** [comment]
I think we need to work with few examples of splitting *lots* to see if we need a distinct stock or we can just use rea:EconomicResource. Let's keep this issue focused on perishable aspect and continue stock/resource conversation in other issues where we already started working with it.

If we split 'lot controlled' resource in multiple ones, they will all have the same lot and expiration date? I think we should repeat the lot nr and expiration date on each instance of rea:EconomicResource and not try to create a foo:Lot instance, which would have expiration date, and which we would reference from instances of rea:EconomicResource.

**Comment by bhaugen** [comment]
> I think we need to work with few examples of splitting lots to see if we need a distinct stock or we can just use rea:EconomicResource.

I'm still not sure exactly what you mean by stock and how it differs from rea:EconomicResource. Sometimes it seems like a possibly-indirectly-identified resource and sometimes like a bin.

> If we split 'lot controlled' resource in multiple ones, they will all have the same lot and expiration date?

Yes. Seems likely that the lot is a separate object with some of its own attributes that are shared by all splits.

>  few examples of splitting lots 

I'll write some of these up as use cases, this is just a drive-by comment to get started under time constraints.
* Dhen splits a large lot of herbs into smaller lots for sale according to order quantity.
* The late lamented Producers and Buyers Co-op split lots of meat in several ways, which I think are fairly standard:
    * An incoming animal was assigned an animal id. All lots of meat coming from that animal could be traced back not only to the animal but also where it came from. This was to trace sources of mad cow, e coli, etc.
    * Each section of the animal after cutting got a lot id that could be traced back to the animal id.
    * When sections were cut into smaller chunks, those got the same lot id as the section.
    * If parts of several animals were combined, as in sausages, the output sausage got a new lot id that could be traced back to all of the input lot ids.

**Comment by bhaugen** [comment]
Common rules seem to be:
* If a source lot is split into several sub-lots with their own destinations, each of the sub-lots keeps the same lot id as its source.
    * Exception: animal id, which may come from a separate animal-tracking system.
* If several different lots are combined, the combination gets its own lot id.

**Comment by elf-pavlik** [comment]
>
* They also combined smaller lots into larger lots for sale to larger orders.
    * The combined lot got a new lot id, which could be traced back to the input lots.

In that case, the merged resource would have expiration date equal to the earliest one from all merged lots?

**Comment by bhaugen** [comment]
> In that case, the merged resource would have expiration date equal to the earliest one from all merged lots?

I think so. It's also possible that lots with different expiration dates do not get combined. I'll ask our cohousing partner who has deep knowledge in this area.

**Comment by bhaugen** [comment]
response:
> Silos (like at Chaseburg) have a capacity (e.g. 100,000 pounds) that is greater than the tank of the hauler picking up farm milk (e.g. 45,000 pounds).  Two loads could be combined in that silo, creating a new Lot number.

> The expiration date of the combined lot would be the older lot.  There is a requirement that farm milk be utilized in production within 72 hours of pickup.  Here again, the older pickup determines the start of the 72 hour period for that combined lot.

**Comment by bhaugen** [comment]
Followup question and reponse:
> Followup question: do you know if your systems have a separate Lot object or record, in addition to the records for the lots in inventory with that Lot ID? So for example, when a lot is split, it would have separate lot inventory records for each split, but one Lot record that each split would reference?

> Response: I am fairly sure that there is a separate Lot record distinct from the inventory itself.

**Comment by elf-pavlik** [comment]
IMO 'expiration' / 'best before' dates make sense as direct attributes of *vf:Resource* instances. Keeping it as just the attribute of Lot and only referencing that lot seeps problematic. Records describing resources would always need to make sure to embed lot details or cache it in some other way in case Lot records becomes unavailable.

One could also look at Lots as a children of particular vf:ResourceType. For example people can consider wine from different years as not substitutable across years.

**Comment by bhaugen** [comment]
I got no problem caching the expiration date on the resource.

**Comment by fosterlynn** [comment]
>IMO 'expiration' / 'best before' dates make sense as direct attributes of vf:Resource instances. Keeping it as just the attribute of Lot and only referencing that lot seems problematic

I agree.

**Comment by elf-pavlik** [comment]
Perishable resources also affect requirement in modeling intents. For example same provider often will have for same 'resource type' different offers for batches approaching their expiry date. I see here 'prototypical' description of resource in intents very useful, intent can refer resource with https://schema.org/SomeProducts `@type` (or VF equivalent) and specify its expiry date. Another offer would have same *vf:model* but no expiry date specified.

**Comment by bhaugen** [comment]
We have some experts in the treatment of perishable resources if you have any specific questions.

One thing about perishable resources, they are almost always lot-controlled.

**Comment by elf-pavlik** [comment]
Maybe you can ask your friend about intents (*vf:Offer*) for resources of same 'resource type' but different 'expiry date'. In common nowadays case, where people request reciprocal transfer of monetary currency, close to expiration products often have offer with lower amount of money.

**Comment by bhaugen** [comment]
I'll ask. One thing I know that they do is that different customers require different expiry dates, probably stated as age of product. Those customer intents are declared as contracts. Some customers will only take "young" products, some will take products closer to their expiration. I assume they charge different prices for those different intents, but don't know for sure.

**Comment by elf-pavlik** [comment]
> I assume they charge different prices for those different intents, but don't know for sure.

sounds related to https://github.com/valueflows/intent/issues/9

**Comment by bhaugen** [comment]
On Wed, Aug 10, 2016 at 6:34 PM, Bob Haugen <bob.haugen@gmail.com> wrote:
> you have explained before how OV handles product expiration and
> age for different customers in the warehouse system. This is another
> question from the Value Flows gang about that, not in terms of the
> warehouse system, but more about what different customers want in
> terms of product "age" (and what you call product "age").

The terminology used is code guarantee.  Code guarantee is the number of days remaining before expiration date at the time of receipt at the customer.  For example, expiration is September 30.  If code guarantee is 30 days for UHT milk then the goods must arrive at the customer no later than August 31.  

> And do you offer different prices for different "ages" of product? For
> example, are customers who demand "young" products charged more than
> those who will accept "older" products?

Short code is product that can no longer be delivered within the standard code guarantee for that commodity.  In order to move this short code product, sales will offer a discounted price.  

There is customer specific code guarantee.  This is when a customer requires more code guarantee than standard.  In the above example, requiring 45 days of code remaining upon receipt.  To my knowledge they are not charged more - typically this is a strategic or high volume customer with some leverage.

> Also, do you discount products as they approach expiration in order to
> sell them faster?

They may also do so for inventory that is very close to becoming short code.  But to be clear, this isn't 'expiration' as in no longer sellable or good product, it is providing the retailer a standard amount of time to move the product off their shelves before it does actually expire.
