### ISSUE TITLE
splitting and merging lots

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#44]
some conversations already exist mostly around splitting lots:
- https://github.com/valueflows/resource/issues/43#issuecomment-225447316
- https://github.com/valnet/valuenetwork/issues/504#issuecomment-225448690

I also see case where we have an input to a process and take part of it from two lot-controlled resources. One could have two events or merge resource needed for the process and have just one event. In some cases, where 'external' agent allocates resource for the process ,they would not expose their internal inventory but only create merged resource and transport it to the location of the process.

**Comment by elf-pavlik** [comment]
>
* Dhen splits a large lot of herbs into smaller lots for sale according to order quantity.
    * Each of the splits had the same lot id as the source lot.
* They also combined smaller lots into larger lots for sale to larger orders.
    * The combined lot got a new lot id, which could be traced back to the input lots.

@fosterlynn would you model such split and merge with an instance of *vf:Process* which
* split: consume A and create B & C
* merge: consume C & B and create C

I don't know if we should consider above *vf:Transformation* or have a distinct subtype of *vf:Process* that doesn't really transform but simply does split/merge.

**Comment by bhaugen** [comment]
> would you model such split and merge with an instance of vf:Process which
> * split: consume A and create B & C
> * merge: consume C & B and create C

Yes. It's potentially a many-to-many relationship and requires an intermediate connector, e.g. vf:Process.

> I don't know if we should consider above vf:Transformation or have a distinct subtype of vf:Process that doesn't really transform but simply does split/merge.

Thus, vf:ProcessTypes. Which, like ResourceTypes, will come in taxonomies. Lots of processes will not transform their inputs. Even assembly processes do not usually transform their inputs, they just attach them together. and can often be disassembled, like a bicycle.

**Comment by elf-pavlik** [comment]
> Thus, vf:ProcessTypes. Which, like ResourceTypes, will come in taxonomies.

I think we should create dedicated issue in `valueflows/valueflows` to clarify how we plan to have commonly shared part of this taxonomy eg. Transfromation, Transportation and how we plan to make it extensible. If we want interoperable environment, we need to have shared understanding. Especially if we want specialized apps with specific UX to work across dataspaces, otherwise we may end up with bunch of spreadsheet / webforms generic tools like https://www.w3.org/2005/ajar/tab

**Comment by bhaugen** [comment]
Good idea! Some taxonomies (or more often lists) of process types exist,  but I haven't seen anything as well-done as the resource type (product) taxonomies. Resource type taxonomies will be important for the wannabe LOD-locecon project, but I figured we could just recommend some and then let people reference, extend, or create their own if they really need to do so. The collaboration requirements will force agreements.

**Comment by elf-pavlik** [comment]
In case of salsa production process. If I want/need to use tomatoes from two different lots, I could
* Have two separate input events, consuming resources from two different lots and together fulfilling single commitment
* Marge needed amount from two lots creating new resource and than consume the whole resource in single event

In cases where I need transportation between place I store tomatoes and place where I make salsa, I would in practice always do the second variant and transport the merged resource to consume it in single event.

**Comment by bhaugen** [comment]
Makes sense to me.

**Comment by elf-pavlik** [comment]
We need YAML for a case where we merge into stock
```yaml
'@id': https://warehouse.example/adfaf#stock
'@type': vf:Stock
'vf:kind': prodont:Mango
'vf:quantity':
          'vf:quantity':
          '@type': qudt:QuantityValue
          'qudt:unit': unit:Kilogram
          'qudt:numericValue': 20
```

another stock with more specific 'vf:kind' (a child or narrower)

```yaml
'@id': https://warehouse.example/fidiosdo#stock
'@type': vf:Stock
'vf:kind': prodont:Ataulfo_(mango)
'vf:quantity':
          'vf:quantity':
          '@type': qudt:QuantityValue
          'qudt:unit': unit:Kilogram
          'qudt:numericValue': 3
```

and we lose the child type information from the stock 'snapshot', but still have trace of it in event of that merge

```yaml
'@id': https://warehouse.example/adfaf#stock
'@type': vf:Stock
'vf:kind': prodont:Mango
'vf:quantity':
          'vf:quantity':
          '@type': qudt:QuantityValue
          'qudt:unit': unit:Kilogram
          'qudt:numericValue': 23
```

**Comment by fosterlynn** [comment]
@elf-pavlik you want to give it a shot, or you want me to give it a shot?  

What is vf:Stock?  Can that be vf:Resource?  (I think it was on your bike examples....)

**Comment by fosterlynn** [comment]
I think use vf:accept, vf:consume, vf:improve??  Doesn't totally fit, but better than vf:consume, vf:consume, vf:create?

**Comment by gcassel** [comment]
Just throwing this in here:  I believe that stocks are groups of [unique instances of resources], each instance of which meets specifications for a defined resource-type.   I think it makes sense to identify vf:Stock as a group of such resources which share owners/usage rights and (probably) are in the same physical location.
