### ISSUE TITLE
how parent/child relationshops between resource types relate to resource instances?

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#46]
Let's say we have a parent resource type, with two children types
- _prodont:Mango_
  - _prodont:Ataulfo_(mango)_
  - _prodont:Tommy_Atkins_(mango)_

When some recipe references _prodont:Mango_, In my plan I could narrow it to one of the children types or also leave it broader and just in observation reference resource with on of the child types.

Similar when casting intents, especially instances of _vf:Request_, to satisfy the recipe with broad _prodont:Mango_ I would just ask for any resource of that broader type. In _vf:Transfer_ I would most likely reference resource of one of the children types, which later I would use in my process.

It also seem to apply to product models, if we have two products which have common parent resource type:
- _prodont:Olive_oil_
  - _itacatealimentos:olive-oil-0.75L-in-wine-bottle_
  - _carbonell:olive-oil-1L-in-metal-can_

In the same process, to satisfy _prodont:Olive_oil_ requirements. I could even mix resources of different product models and use that mix on input.

Related to #44, when we merge lots from two different product types, which share common resource type parent, we can use that common parent as _vf:resourceType_ of that merged resource, since non of the specific product types will apply any more.

**Comment by bhaugen** [comment]
I agree with most of that, but think it would be possible but maybe unusual for a combined lot of different child resource types but a common parent resource type to use the common parent as the resource type of the combined lot.

I am not sure of that, but for example, when I see wines that blend different varieties, they usually identify all of the varieties on the label, and the combination usually has a different resource type, apparently sometimes with a famous name.
http://winefolly.com/tutorial/famous-wine-blends/

**Comment by elf-pavlik** [comment]
I think we need to collect in #26 some examples of how vendor defined (and specific) product models relate to commonly defined (and generic) resource types. For example if tomatoes producers defined their vendor specific product types, I could easily mix different one in same salsa production process. Often recipe will not reference vendor specific product model but just generic resource type, similar with intents based on those generic recipes.

**Comment by fosterlynn** [comment]
It seems fine if you have a recipe that consumes prodont:mango, and you actually consume a couple resources of different mango resource types in your process.  The computer system just needs to be able to process the hierarchical taxonomy. 

And if you accept the model where an input resource is decremented and an output resource is incremented when you receive something in a transfer, none of this is an issue.  Same for transportation.  If you receive Heinz tomatoes, and just add to or create your general tomato resource, not a problem. Seems like serial numbers or lot numbers could survive a resource type change too.

This makes me think about using @type for resource types.  Possibly problematic?

**Comment by elf-pavlik** [comment]
> This makes me think about using @type for resource types. Possibly problematic?

When we use `@type` for resource types. That implies that instance of some child type is at the same time instance of all the parent types. Assuming that we use *rdfs:subClassOf* to define child/parent relationships between resource types and define resource types as classes - instances of *rdfs:Class*.
