### ISSUE TITLE
assembled resource listing its components

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#48]
I started thinking around use case which involves assembling bicycles. We already have some conversations around assembly process, one of IMO very relevant comments in https://github.com/valueflows/process/issues/5#issuecomment-219119262

> @bhaugen 
> Consumed is about resources that are gone when they go into a process. We could even differentiate assembly vs incorporation (I know there's a better word for incorporate but can't find it now: the diff is that assembled inputs can be disassembled, incorporated ones can't).

Bicycles get assembled from parts, some of them (like the frame) can have serial number. The assembled bike resource could list all the components (resources used in assembly, not stocks they came from). The parts could have relationship with a resource through n-ary array which would represent a slot (e.g. front break) similar as 'index' property in http://smiy.sourceforge.net/olo/spec/orderedlistontology.html#sec-example

**Comment by bhaugen** [comment]
Yup. In the manufacturing world, this is called a [bill of lots](http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=6360742&url=http%3A%2F%2Fieeexplore.ieee.org%2Fiel5%2F6337024%2F6360685%2F06360742.pdf%3Farnumber%3D6360742) or [bill of serial numbers](http://www.telecomadvisors.org/dcl1.6/index.php?snpm_brochure_en.pdf).

**Comment by elf-pavlik** [comment]
related comment https://github.com/valueflows/process/issues/1#issuecomment-136420374

**Comment by bhaugen** [comment]
This is pretty easy to assemble from input events. In general, such assemblies use subassemblies for e.g. front breaks, and the sub-assembly will tell you which components went into the front break.

**Comment by bhaugen** [comment]
In other words, no need for an index property (unless I am missing something).

**Comment by elf-pavlik** [comment]
I want to write example process with assembly of two bikes during one working session of bike workshops. Both frames have serial number as well as both resulting bikes have serial numbers. To know which bikes has which frame you may need distinct process for each bike. At the same time the usage of workspace and work one might want to describe as inputs to a single process. This may also give a good use case for sub processes. I just want to point out that if you want to only rely on events, it may require much more granularity in recording processes. If resource can have a list of included components one could preserve information of which frame each bike has while having single process which takes two frames as input and outputs two bikes.

**Comment by bhaugen** [comment]
The events are to specify which inputs were actually used. The process cannot tell you that. Nor can the plans. Things change, shit happens.

**Comment by elf-pavlik** [comment]
If you have
* one process
* two 'consume' events (one per frame)
* two 'create' events (one per bike)

You **don't** know which bike has which frame

If you have 
* two processes 
* one 'consume' event for frame (per process)
* one 'create' event for bike (per process)

You **do** know which bike has which frame

If you have
* one process
* two 'consume' events (one per frame)
* two 'create' events (one per bike)
* each bike lists its components

You **do** know which bike has which frame

**Comment by fosterlynn** [comment]
>I want to write example process with assembly of two bikes during one working session of bike workshops. 

That is an interesting use case.  I'm not sure I like sub-processes for it, but then again, I'm not sure how I would solve it.  A lot of assembly line processes might have this issue.

**Comment by bhaugen** [comment]
I think if you are concerned about tracking serial and lot IDs, you need to break up your processes to enable that. Which means more processes, one way or another.

I can ask how lot tracking works in that regard. Don't know anybody who does serialized manufacturing, and the software doc I saw was not detailed enough to answer that kind of question.

**Comment by bhaugen** [comment]
> I can ask how lot tracking works in that regard.

Actually, I know how lot tracking works. One process produces one and only one output lot.  

Lot tracking in the US anyway is regulated by the Food & Drug Administration, and they don't allow multiple lots in and multiple lots out. I have their handbook somewhere in some book box. Just don't ask me to find it...

**Comment by fosterlynn** [comment]
>Actually, I know how lot tracking works. One process produces one and only one output lot. 

@bhaugen So, if a lot changes on an input, that would trigger a new process?  And also a new output lot?

**Comment by bhaugen** [comment]
>  if a lot changes on an input, that would trigger a new process? And also a new output lot?

How would the lot change? Combining lots into a new lot, as we saw in DHen, requires a process where the lots to be combined are inputs and the new lot is an output. But normally lot IDs do not change once given. A context agent have a lot ID generation rule and all lots within in that context will have automatically-generated lot IDs following that rule. I think for GTINs the format is standardized.

**Comment by fosterlynn** [comment]
From offline discussion:  This is about processing the same output resource type from the same input resource types.  If the lot number changes on an input, yes it does trigger a new process and a new output lot number.
