### ISSUE TITLE
timeline based stocks (availability?) for Usage and Services 

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#51]
in https://github.com/valueflows/valueflows/issues/148#issuecomment-239818476 @bhaugen writes: 

> The [Quick Response Engine](https://en.wikipedia.org/wiki/Quick_Response_Engine) (QRE)  was a skunkworks project for an ERP software company I worked for in the 1990's, and was also my first implementation of the set of ideas that fed into VF.  
> 
> We did shift scheduling for people and equipment in that project. The inventory of such time-based resources was a shift calendar composed of 15-minute slots. It was implemented as sparse array composed only of slots where the resource was scheduled to be available: for a person, the shifts they were scheduled to work. Each time-based resource had a shift calendar. A process could reserve as many of these 15-minute slots as it needed, assuming they were not already taken by some other process.

For _work_ and _use_ #29  type events we need a way to describe a resource/stock #41. I would consider describing timeline of availability as stock in which we can create 'logical resources' which we can reference in allocations #39

**Comment by bhaugen** [comment]
In QRE, these were plans, Manufacturing planning systems for fast-moving environments often allocate resources that do not exist yet: that is, planned resources. Any time-based resource is like that.

As Lynn and I discussed in our morning walk, another aspect of these time-based commitments is Now. When Now passes, all such commitments that have not been used are dead. They don't exist anymore.

(Now has a lot of peculiarities as a concept, which we discovered as we implemented this stuff, which I will save you from Now....)

**Comment by fosterlynn** [comment]
Wondering if vf:UsageResource should become vf:TimeBasedResource? Could handle equipment and space, plus work....

**Comment by fosterlynn** [comment]
Here's an attempt to think about how the vf:Resources might look.  Could be very wrong....

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/d8f97d89#stock
'@type': vf:Resource
'vf:model': ord:ORD-FDM-3D-printer
'vf:serialNumber': d8f97d89
'vf:quantity':
  '@type': qudt:QuantityValue
  'qudt:unit': unit:Each
  'qudt:numericValue': 1
```
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/d8f97d89#usage
'@type': vf:TimeBasedResource
'vf:category': sens:EquipmentUsage
'vf:underlyingResource': https://fablab.example/d8f97d89#stock
'qudt:unit': unit:Day  
'vf:contains':
    - '@id': https://fablab.example/d8f97d89-20160815#usage
    - '@id': https://fablab.example/d8f97d89-20160816#usage
    - '@id': https://fablab.example/d8f97d89-20160817#usage
    - '@id': https://fablab.example/d8f97d89-20160818#usage
    - '@id': https://fablab.example/d8f97d89-20160819#usage
```
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/d8f97d89-20160815#usage
'@type': vf:TimeBasedResource
'vf:start': 2016-08-15
'vf:end': 2016-08-15
```
(etc.)

And sorry about the qudt:unit, can't think about that right now.  Also I'm sure we can do dates and times using some existing thing, just don't want to look now.  And find a good calendar model.

**Comment by fosterlynn** [comment]
Or maybe:
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/d8f97d89-20160815#usage
'@type': vf:TimeBasedResource
'vf:start': 2016-08-15
'vf:durationQuantity':
  '@type': qudt:QuantityValue
  'qudt:unit': unit:Day
  'qudt:numericValue': 1
```

**Comment by bhaugen** [comment]
Does qudt handle time units properly? If so, it should provide something for duration. If not, maybe we should use something else for units of time.

**Comment by elf-pavlik** [comment]
How would we represent quota / agent? In https://github.com/valueflows/resource/issues/29#issuecomment-225283791 I proposed use case:
>
* 5 people co-own 3D printer
* each of them has 20% of availability to use it
* they do reservations (commitments) dynamically (first come first served) using a monthly quota
* each of them can transfer the rights to any part of their share of printer availability, this creates a sub quota to use in reservations

I think we could create 'logical resources' which represents a month period of usage. Than it would contain further 'logical resources' which would represent each monthly quota and different agents could own it. In each of those one could create further 'logical resource' to represent each allocation/booking. I think we need to ask @ahdinosaur to help us with this holo madness 😉
