### ISSUE TITLE
vf:KnowledgeResource

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#53]
based on: https://github.com/valueflows/process/issues/1#issuecomment-241081774

> ingredient, product, component - and actually, this may also need to refer to electronic resources such as documents and designs, come to think of it (maybe a different name or an additional type...)

I would like to quickly capture the difference between 'knowledge resource' and 'digital document'. I knowledge resources people value the knowledge it captures, on wouldn't measure it in KB. For digital resources like documents, we may measure them in KB considering storage and bandwidth. 

I see it related to https://en.wikipedia.org/wiki/HTTPRange-14

In most cases a 'knowledge resource' will have a 'digital document' that provides an interface to access that knowledge. Still we preferably see them as distinct resources.

**Comment by bhaugen** [comment]
In NRP, knowedge resources were cited. We did not count knowledge resources that were not documented. That came from experience. While I would not take every bit of everything from NRP, I would take restriction. This is also related to provenance.

**Comment by fosterlynn** [comment]
How about vf:KnowledgeResource for the embodied knowledge; and the digital form is a vf:MaterialResource, when we need that?

**Comment by elf-pavlik** [comment]
I think that material resources and digital resources have enough of difference in behavior that we can define distinct class for digital resources. They will have media type, KB size etc. but no geolocation, spacial dimensions or mass.

**Comment by fosterlynn** [comment]
>I think that material resources and digital resources have enough of difference in behavior that we can define distinct class for digital resources. They will have media type, KB size etc. but no geolocation, spacial dimensions or mass.

I think you will find equally as many differences between other examples of material resources, there is a wide variety!  So for now, I don't think it warrants a new type.  Let's see what happens with specific use cases when we get them.

**Comment by fosterlynn** [comment]
Let's discuss the questions of how to quantity citations in the vocab, ref. objection to using vf:eventQuantity here https://github.com/valueflows/process/issues/21#issuecomment-238117961.

**Comment by fosterlynn** [comment]
Thinking about this a little more: If we want a new type, maybe it should vf:DigitalResource?  Knowledge gets into a whole bunch of subjective things, and is sort of apples and oranges with vf:MaterialResource.  For example, the material resource of a paper book has a big knowledge component.  If we just speak of digital resources vs material resources, then it is more clear the different effects of events on them, where digital resources can be copied or used as many times as you like with no effect on the original.

(There is overlap here with types of events, which I'm still puzzling about.)

**Comment by elf-pavlik** [comment]
> Thinking about this a little more: If we want a new type, maybe it should vf:DigitalResource? 

👎 both *vf:DigitalResource* (file, web resource) or *vf:MaterialResource* can provide interface to access the *vf:KnowledgeResource*. I don't think knowledge resources have any quantity or unit, knowledge doesn't seem to me as something we can measure this way.

I would propose to don't tackle on knowledge resources in 0.0 or even 0.1 - 0.3 we may need more use cases to address it properly.

> Let's discuss the questions of how to quantity citations in the vocab

Once we want to give it more focus, we may need some well documented use cases which exemplify what kind of quantities people would like to use.

**Comment by fosterlynn** [comment]
>I would propose to don't tackle on knowledge resources in 0.0 or even 0.1 - 0.3 we may need more use cases to address it properly.

:+1:   

It may not even want to be part of this vocabulary.  (Not saying knowledge isn't important of course.  Just that its planning, coordination, accounting, etc. is not the same thing and maybe would never be done really.  Knowledge needs to be free. :relaxed: )

>>Let's discuss the questions of how to quantity citations in the vocab

>Once we want to give it more focus, we may need some well documented use cases which exemplify what kind of quantities people would like to use.

I actually gave usage and citations a lot of thought yesterday, but haven't written it up yet, will do soon.

**Comment by bhaugen** [comment]
> Just that its planning, coordination, accounting, etc. is not the same thing and maybe would never be done really. 

Depending on what you include in knowledge resources (e.g. designs?), they are planned and coordinated all the time, and they take economic resources (e.g. at least work) to produce.

**Comment by fosterlynn** [comment]
>Depending on what you include in knowledge resources (e.g. designs?), they are planned and coordinated all the time, and they take economic resources (e.g. at least work) to produce.

I was responding to @elf-pavlik 's thought of knowledge resources being defined separately from their physical (including electronic) existence - valuing the knowledge itself only. That would be in addition to the material or electronic or service resource.

I myself would just bury the knowledge component in the resource we naturally talk about when we coordinate.  And even when we cite, when the main value is the knowledge.  But you cite a document, and I'm happy with just having the document be the resource.

And we both agreed it could be looked at later with a use case.  :)

**Comment by bhaugen** [comment]
The rule in Sensorica was that if it was not documented, it did not count.
