### ISSUE TITLE
Can we support faceted classification?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/resource#54]
Might be related to this too https://github.com/valueflows/resource/issues/46.

Faceted classification is prevalent in searching for a resource: Like color: red, size: 12, type: dress, etc.  You need both parts, for example "color" is the facet, "red" is the facet value.

Right now we have vf:category and vf:model as properties of a vf:Resource, which are parts of documenting what a resource is.  vf:category comes the closest to using faceted classification, but I don't think it actually works that way?  @elf-pavlik you could correct me if I'm wrong.

How would we best support it?

**Comment by elf-pavlik** [comment]
Color, size etc. look to me like filters which one can include when querying given dataset. 

Resources of different types will have all kind of different attributes that apply to particular type but not other types. Applications focused on specific domains will most likely include queries which allow intuitive filtering data in that particular domain.

**Comment by gcassel** [comment]
I'm a big fan of composite description and faceted classification.  Some historic reference btw (not much):  https://github.com/valueflows/resource/issues/2

Vf may need to pick one term such as composite/composition, faceted or multivariate.   I'm thinking that composition is a most appropriate and versatile root term.  If desirable, we could even distinguish the description of composites and *compounds*.   In chemistry, of course, a compound has emergent properties which aren't present in its constituent elements.
