### ISSUE TITLE
add few more examples of resources to start working on relationships

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#6]
In similar [selfdogfood](http://indiewebcamp.com/selfdogfood) spirit as https://github.com/valueflows/agent/issues/29
#### Spec
- [x] ValueFlows Vocab - [valueflows.jsonld](https://github.com/valueflows/resource/blob/master/examples/valueflows.jsonld)
#### SourceCode
- [ ] https://github.com/elf-pavlik/webprofiled
- [ ] https://github.com/openfoodfoundation/openfoodnetwork
- [ ] https://github.com/valnet/valuenetwork
- [x] https://github.com/holodex
- [ ] https://github.com/cobudget
- [ ] https://github.com/loomio
- [ ] https://github.com/metamaps

I would propose to keep Resource - sub -> Resource relationships details for later and start with simplest possible cases. I hope ASAP we will get examples with [@id / url](https://github.com/valueflows/valueflows/issues/45) hosted on at least 4-5 different domains which will allow testing apps getting data from multiple sources, for now via most simple HTTP GET with header "Accept: application/ld+json"

@bhaugen @fosterlynn @ahdinosaur @Connoropolous

**Comment by bhaugen** [comment]
@elf-pavlik - please explain "Resource - sub -> Resource"? (I'm happy to keep them for later, but I don't know what all you intend or would include in that relationship. Like, for example____?)

Re ASAP: are you proposing to make this a higher priority than finishing the agent vocab round trip?

**Comment by elf-pavlik** [comment]
> Re ASAP: are you proposing to make this a higher priority than finishing the agent vocab round trip?

I see need that we pick general pattern for expressing any kind of relationships, very likely building around [rdf:Property, Reification, QualifiedRelations and Nary-Relations](https://github.com/valueflows/valueflows/issues/63). Once we agree on our general approach, we can start looking where relations(hips) between different kind of entities need further specializations eg. Agent -> Agent, Agent -> Resource (and or Resource -> Agent)

> please explain "Resource - sub -> Resource"? (I'm happy to keep them for later, but I don't know what all you intend or would include in that relationship. Like, for example____?)

https://github.com/cobudget - sub -> https://github.com/cobudget/cobudget-api
https://github.com/cobudget - sub -> https://github.com/cobudget/cobudget-ui

Sometimes one may want to make statements about cobudget as fully functional software stack which one can provide as hosted service, and sometimes one may want to make statements about particular components of that stack - api, ui-A, ui-B ...

**Comment by bhaugen** [comment]
I agree that picking the pattern is ASAP.

Understand now what you mean by sub->resource. No problem deferring.
